### ISSUE TITLE
address_manager.py support for systems without iproute2

### ISSUE THREAD

**Issue by ok-devalias** [GoogleCloudPlatform/compute-image-packages#110]
Currently, these scripts only work for Linux systems.  In particular, porting address_manager.py would allow for FreeBSD and potentially other UNIX systems to use the load balancing side of GCE.  I have been attempting to translate the "ip route add to local $IP/32 dev eth0 proto 66" command, but so far I've had no luck.  Looks like "-proto2" can replace "proto 66."

I've tried:
- route add -host $LB_IP -iface vtnet0 -nostatic -proto2
- route add -host $LB_IP $HOST_IP -nostatic -proto2

**Comment by bsiegert** [comment]
Any update on this? Looking into porting this to NetBSD.

**Comment by zmarano** [comment]
address_manager has been deprecated in favor of the ip_forwarding_daemon.  At this point we only support Linux in the "Linux guest environment'. However, we do accept PR's if you have a specific change in mind that would solve this elsewhere.
