### ISSUE TITLE
desired_accounts.py logging.info is too chatty in syslog

### ISSUE THREAD

**Issue by talfco** [GoogleCloudPlatform/compute-image-packages#113]
The code "logging.info('Google SSH key schema identifier found.')" will result in two entries per minute in the syslog which is too spammy like and makes remote-monitoring more complex. 

» 12:15:43.273 rubystackbox-xxx accounts-from-metadata: INFO Google SSH key schema identifier found.
» 12:15:43.400 rubystackbox-xxx accounts-from-metadata: INFO Google SSH key schema identifier found.
» 12:16:43.323 rubystackbox-xxx accounts-from-metadata: INFO Google SSH key schema identifier found.
» 12:16:43.450 rubystackbox-xxx accounts-from-metadata: INFO Google SSH key schema identifier found.

**Comment by jkaplowitz** [comment]
This got released in our images dated 20150309 and compute-image-packages version 1.2.3. Thanks!
