### ISSUE TITLE
ssh keys regenerated when none are present

### ISSUE THREAD

**Issue by swills** [GoogleCloudPlatform/compute-image-packages#144]
The regenerate-host-keys script regenerates ssh keys in all cases, even when none are already preset or baked into the image, logging something like this:

regenerate-host-keys: Regenerating SSH Host Keys for:  (previously ).

Perhaps it could check that there was no previous IP/ssh key and not regenerate in that case? I could work on this and send a pull request, but wanted to got feedback on the idea first.

**Comment by illfelder** [comment]
It only needs to be filled out once, but here's the link again: https://cla.developers.google.com/clas

(and, once again, thanks you!)

**Comment by swills** [comment]
Signed this in 2011, but updated to add my github username, should be good now?

**Comment by illfelder** [comment]
The code changes you made no longer appear associated with this issue. Do you still have code changes for review in your local branch?
