### ISSUE TITLE
SyncAddresses exception: Cant check local addresses

### ISSUE THREAD

**Issue by wenzowski** [GoogleCloudPlatform/compute-image-packages#148]
Is this the host project for [google-address-manager](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-daemon/etc/init.d/google-address-manager)?

I am completely clueless as to what this script is supposed to be doing, and why it's failing on coreos. Perhaps this is related to coreos/bugs#245?

```
Feb 23 20:23:37 core1.c.deis-dialoghq.internal google-address-manager:  WARNING Non-zero exit status from: "/usr/bin/ip route ls table local type local dev ens4v1 scope host proto 66"
Feb 23 20:23:37 core1.c.deis-dialoghq.internal google-address-manager:                                                                              STDOUT:
Feb 23 20:23:37 core1.c.deis-dialoghq.internal google-address-manager:                                                                              STDERR:
Feb 23 20:23:37 core1.c.deis-dialoghq.internal google-address-manager:                                                                              Cannot find device "ens4v1"
Feb 23 20:23:37 core1.c.deis-dialoghq.internal google-address-manager:  ERROR SyncAddresses exception: Cant check local addresses
```

**Comment by jkaplowitz** [comment]
Hi @wenzowski,

Yes, this is the host project. While we don't have the resources to focus on CoreOS support, we'd welcome a pull request that generalizes the detection of the Ethernet interface name in a way that would improve behavior on CoreOS. Thanks for reaching out!

**Comment by wenzowski** [comment]
Thanks for confirming @jkaplowitz. I think I now understand [the purpose](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-daemon/usr/share/google/google_daemon/address_manager.py#L15) but why does it need to autodetect the interface name? A quick `ifconfig` shows eth0 with internal inet and inet6. Is this daemon supposed to be watching for new interfaces, or just updating the addresses existing interfaces are bound to?

**Comment by jkaplowitz** [comment]
I'm not honestly sure how CoreOS's version of the code is finding ens4v1, as indeed our code shows eth0 only. From the issue you linked and the error you gave, it looks like they swapped out one hard-coded value (eth0) for another (ens4v1), but then used a newer version of udev which no longer exposes the name ens4v1. Maybe they have patched our code?

I believe the intention of our code is to manage IP addresses on the first Ethernet interface, regardless of its name. The code merely assumes that the name is eth0 (our tree) or ens4v1 (possibly true in CoreOS's version), but determining this in a general way would be great.

**Comment by wenzowski** [comment]
Hmm, I'll have to look into this a little more myself then. Thanks @jkaplowitz

**Comment by jkaplowitz** [comment]
No problem. Good luck!

**Comment by joshk0** [comment]
(Hey Jimmy!)

It was alluded to earlier, but I'll repeat with supporting evidence so this is concrete: The reason that CoreOS is pulling out ens4v1 is [this patch](https://github.com/coreos/coreos-overlay/blob/master/app-emulation/google-compute-daemon/files/0001-hack-address_manager-use-CoreOS-names-and-locations.patch).

On our GCE CoreOS deployment, some machines have eth0 (n1-highmem-4) and other machines (n1-standard-1) have ens4v1. Is there some sort of affinity there or is it a red herring?

Anyway, in terms of writing a patch, it's clear that finding a generic way to find the first Ethernet interface will make this moot. However, what defines the 'first Ethernet interface'? Would an easy rule of thumb be "the first interface through which metadata service requests succeed'?

**Comment by joshk0** [comment]
I'm still willing to help, was just waiting for an answer.

**Comment by zmarano** [comment]
Hi Joshua,
CoreOS is supported by the CoreOS project directly. If this issue still exists, it would be better to post a question to CoreOS bugs. https://github.com/coreos/bugs or the coreos-dev group https://groups.google.com/forum/#!forum/coreos-dev

**Comment by cyhex** [comment]
I have the same issue using default Google cloud supplied Ubuntu 16.04 LTS

`
$ ifconfig
ens4      Link encap:Ethernet  HWaddr 42:01:0a:84:00:02  
          inet addr:10.132.0.2  Bcast:10.132.0.2  Mask:255.255.255.255
          inet6 addr: fe80::4001:aff:fe84:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:27562 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32211 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:130895615 (130.8 MB)  TX bytes:4668347 (4.6 MB)

`

**Comment by shtse8** [comment]
I have the same issue using default Google cloud supplied Ubuntu 16.04 LTS

**Comment by zmarano** [comment]
Please see https://github.com/GoogleCloudPlatform/compute-image-packages/issues/217
Canonical is working on resolving this issue in Ubuntu 16.04.
