### ISSUE TITLE
Startup scripts broken for SUSE images

### ISSUE THREAD

**Issue by erjohnso** [GoogleCloudPlatform/compute-image-packages#155]
With the changes introduced in https://github.com/GoogleCloudPlatform/compute-image-packages/commit/502f06e6d438d30d5cc632f37bb8256fa4ec65c8, the startup scripts no longer work on SLES or OpenSUSE images since there is no such file, `/lib/init/vars.sh` (e.g. https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-startup-scripts/etc/init.d/google-startup-scripts#L27).

Currently, SLES / OpenSUSE are still using the 1.1.9 release so startup scripts are mostly working. AFAICT, the only missing functionality is `shutdown-script` support.  However, the next time that the images are rolled with an updated set of packages, none of the startup scripts will work (well, perhaps SLES12 will).

/cc @jeremyje @illfelder

**Comment by illfelder** [comment]
This is no longer an issue so I am closing this off.
