### ISSUE TITLE
console logging in google-startup-scripts

### ISSUE THREAD

**Issue by jgleissner** [GoogleCloudPlatform/compute-image-packages#177]
Hi,

The rsyslog config in google-startup-scripts/etc/rsyslog.d/90-google.conf configures kernel and other messages to be dumped to the console, which makes console virtually impossible. Is there are reason for this?

Regards
Joe

**Comment by illfelder** [comment]
We include kernel messages in case there is a failure on boot. The latest GitHub release contains a new Linux guest environment which limits the other logs that are written to the console.
