### ISSUE TITLE
Wrong Live Migration link

### ISSUE THREAD

**Issue by tweksteen** [GoogleCloudPlatform/compute-image-packages#186]
The link in [google-daemon README](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-daemon/README.md#google-daemon) named "Live Migration" does not resolve properly. The scheme needs to be added.

**Comment by null0000** [comment]
I can update this. In the mean time, [here's](http://googlecloudplatform.blogspot.com/2015/03/Google-Compute-Engine-uses-Live-Migration-technology-to-service-infrastructure-without-application-downtime.html) the actual link

**Comment by illfelder** [comment]
I submitted a PR to fix the issue - the only problem was a missing https:// in front of the link.

**Comment by illfelder** [comment]
This is merged - closing this issue off.
