### ISSUE TITLE
NVMe image is flawed

### ISSUE THREAD

**Issue by joshk0** [GoogleCloudPlatform/compute-image-packages#198]
Hi there, sorry if this is the wrong place for this.

I notice that the special Debian NVMe image you have prepared has a custom kernel deb. It is versioned such that future backports from Debian will erase the NVMe patched kernel unless you pay attention to it. The best way to avoid this is to not use the same package name as the upstream one. Additionally, it would be nice to have the original deb available in a Debian repository somewhere, as well as the nvme patch itself so we can inspect its contents. I had to repack it myself from a different machine which had the same kernel because I mistakenly upgraded it.

If you did all of this, you probably wouldn't have to pin the package in /etc/apt/preferences.d.

I'm happy to help with this but am not sure if the source for this is tracked in github at all.

Thanks!

**Comment by zmarano** [comment]
While there isn't a perfect solution for Debian at the moment- the Ubuntu 16.04 and 16.10 images on GCE now have optimized NVMe drivers built in.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1637565

For all intents and purposes the Debian image is EOL and will be removed in due order.

The NVMe optimizations are being upstreamed to the Linux kernel- it is just taking awhile.
https://www.collabora.com/news-and-blog/blog/2016/08/23/increased-performance-of-emulated-nvme-devices/
