### ISSUE TITLE
Spamming warning message

### ISSUE THREAD

**Issue by baconcheeseburger** [GoogleCloudPlatform/compute-image-packages#214]
I'm currently being spammed with the error message:

```
Apr 11 20:00:51 [secret-node-name] accounts-from-metadata: WARNING Not creating account for user [user].  Usernames must comprise characters [A-Za-z0-9._-] and not start with '-'.
```

What's up with that?!?

**Comment by illfelder** [comment]
It appears the image you are running on doesn't accept "user" as a valid username. If you remove SSH keys with the username "user" you should stop getting spammed. We will look into reducing spam in general for invalid keys.
