### ISSUE TITLE
google-adress-manager is broken on Ubuntu Xenial 16.04

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [GoogleCloudPlatform/compute-image-packages#217]
address-manager fails on the current image of 16.04 server because the network interfaces have been renamed: 

```
 google-address-manager[7151]: WARNING Non-zero exit status from: "/sbin/ip route ls table local type local dev eth0 scope host proto 66"
                    STDOUT:

             STDERR:
          Cannot find device "eth0"
```

I am getting such an error every 5 seconds. See also https://bugs.launchpad.net/juju-vagrant-images/+bug/1547110 or https://github.com/geerlingguy/packer-ubuntu-1604/issues/1 for (some) of the other manifestations of this change.

**Comment by israelfaria** [comment]
I did hit this too. The solution is quite simple:
Change line 110 on address_manager.py to
`cmd = ('{0} route ls table local type local dev **ens4** scope host ' +`
For some reason naming scheme of network interfaces has been changing in ubuntu. It seems to be related to systemd. Anything assuming network interface is eth0 should be revised.

**Comment by MatthiasWinkelmann** [comment]
I got the impression that the network interface IDs are now subject to change without notice, which would make this a temporary solution at best... But we'll see.

**Comment by zmarano** [comment]
Thanks for reporting this! We are aware of this issue and working with Canonical on a fix for Ubuntu 16.04. We also have a fix in the works to make this user or provider configurable. Stay tuned.

**Comment by CrackerJackMack** [comment]
@zmarano you have a link to the launchpad bug so we can follow along?

**Comment by zmarano** [comment]
Canonical has released the patch into Xenial. You should get the fixed version if you update your instance (apt-get update; apt-get dist-upgrade). Also new instances based on ubuntu-1604-xenial-v20160429 will have this fix.

**Comment by sbadia** [comment]
For the record…
```
# zcat /usr/share/doc/gce-daemon/changelog.Debian.gz|head -20
gce-utils (1.3.3-0ubuntu4~16.04.0) xenial; urgency=medium

  * Backport to 16.04

 -- Daniel Watkins <daniel.watkins@canonical.com>  Tue, 26 Apr 2016 11:01:13 +0100

gce-utils (1.3.3-0ubuntu4) yakkety; urgency=medium

  * Don't assume (in address manager) that the network interface will be eth0.

 -- Daniel Watkins <daniel.watkins@canonical.com>  Mon, 25 Apr 2016 17:54:22 +0100
```

**Comment by shanipribadi** [comment]
```
+
+def get_first_ens_interface():
+    candidates = [iface for iface in os.listdir('/sys/class/net/')
+                  if iface.startswith('ens')]
+    return candidates[0]
+
+
```
I'm getting exception on that function call. After upgrading to ubuntu 16.04 from 14.04 the ethernet is still named eth0, and not changed to ensxx in my case.
The function is returning exception since if `candidates == []`, then `candidates[0]` will fail with `IndexError`.

**Comment by illfelder** [comment]
We have a new version of the IP forwarding daemon in our development branch. It should contain a fix for this issue as well as the more general problem of determining the default ethernet interface.

New code for reference:
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/development/google_compute_engine/ip_forwarding/ip_forwarding_utils.py#L71

**Comment by zmarano** [comment]
Let me check with Ubuntu on this- if you did an in-place upgrade from 14.04 to 16.04, you may need to enable a different repository which would contain the updated package.

**Comment by shanipribadi** [comment]
@zmarano yes, I did an in-place upgrade from 14.04 to 16.04, 
I found this
http://launchpadlibrarian.net/262736324/gce-utils_1.3.3-0ubuntu4_1.3.3-0ubuntu5.diff.gz
That basically adds `eth` as another allowable interface name.. I'm using that patch for now. Thank you very much..

**Comment by maksymov** [comment]
any news? still not work in GCP

**Comment by zmarano** [comment]
@maksymov What specifically are you having problems with?
16.04+ introduced [predictable network interface names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/). The Ubuntu software for GCE has been updated to reflect these changes.
