### ISSUE TITLE
IsUserSudoerEntry does not escape regex

### ISSUE THREAD

**Issue by mattjo** [GoogleCloudPlatform/compute-image-packages#218]
The [IsUserSudoerEntry](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-daemon/usr/share/google/google_daemon/accounts.py#L47) function does not escape regex characters in the user name, so if there are two users on the system, test.user and test_user, the test.user will never be added since test_user matches the regex.

**Comment by illfelder** [comment]
We are rewriting the Linux accounts daemons; as part of the change, we will be adding users to a group, so weird regex parsing of users won't be necessary.

**Comment by illfelder** [comment]
The rewrite is now compete and can be reviewed in the development branch of compute-image-packages.

**Comment by illfelder** [comment]
The latest GitHub release contains the new Linux guest environment, and fixes this issue.
