### ISSUE TITLE
CoreOS support: build a container image

### ISSUE THREAD

**Issue by philips** [GoogleCloudPlatform/compute-image-packages#264]
In order to make this work under CoreOS we should build a container image. The container image needs to execute under rkt so that the packages can live under systemd monitoring. 

Essentially the first pass will be a Dockerfile or some other container image builder. This will probably take a similar distribution design to https://github.com/coreos/bugs/issues/1303

@crawford will take a first look at this.

**Comment by dm0-** [comment]
CoreOS alpha now includes the GCE agent scripts in a container.  Unless there is ongoing upstream work to provide a container, I think this can be closed.
