### ISSUE TITLE
Ubuntu 16.04 Image starts with wrong hostname in rsyslog managed logs

### ISSUE THREAD

**Issue by gottwald** [GoogleCloudPlatform/compute-image-packages#290]
This has been reported to the GCE Bug Tracker: https://code.google.com/p/google-compute-engine/issues/detail?id=354
I was asked to report this here:

__What steps will reproduce the problem?__
1. Start a VM with the Image `ubuntu-1604-xenial-v20160610` and give it a random name
2. Log in
3. Create a testlog entry with `logger testlog-entry`
4. Check the syslog file with `tail -n20 /var/log/syslog`

__What is the expected output? What do you see instead?__
I'd expect to see the instance hostname in the log. 
I see `ubuntu` instead which might have been the hostname during image build.

__What version of the product are you using? On what operating system?__
`ubuntu-1604-xenial-v20160610`

__Please provide any additional information below.__
If I repack the image with packer, and start a instance with the new packer image, I see the temporary packer instance ID, not the expected hostname that is set at instance creation.

After a restart of the rsyslog daemon and an additional testlog-entry the correct hostname is shown in the logs for new messages.

Did the same test with `ubuntu-1404-trusty-v20160610.`
The 14.04 Image does not have this problem.

**Comment by zmarano** [comment]
Hi Ingo,
We are asking Canonical about what is different between 16.04 and 14.04 in this regard. I suspect it has something to do with systemd dependencies differing from upstart in 14.04 but I will get back to you when we know something more.

**Comment by zmarano** [comment]
You can track progress here: https://bugs.launchpad.net/cloud-images/+bug/1599810
Since this isn't a bug with the software in this project, I am going to close the issue out.

**Comment by gottwald** [comment]
Thx!
