### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by OddBloke** [GoogleCloudPlatform/compute-image-packages#317]
The test failures that I was seeing during Ubuntu packaging were fixed in 709a82adbac3b41bf3f7f23dd29ef9112eaf7fe6; a new release including that commit would make my life much easier. :)

**Comment by illfelder** [comment]
I've created a prerelease:
https://github.com/GoogleCloudPlatform/compute-image-packages/releases/tag/20160803

We will need to build new images and verify they work properly before promoting it to a release, but you should be able to use the pre-release for your own testing. Nothing will change between the pre-release and release as long as no bugs are discovered.

**Comment by zmarano** [comment]
Forgot to close this issue out. The release is here.
https://github.com/GoogleCloudPlatform/compute-image-packages/releases/tag/20160803
