### ISSUE TITLE
NetworkInterfaces section of /etc/default/instance_configs.cfg undocumented

### ISSUE THREAD

**Issue by OddBloke** [GoogleCloudPlatform/compute-image-packages#329]
I'm trying to work out if I need to set anything in the NetworkInterfaces section of /etc/default/instance_configs.cfg.template for the Ubuntu packaging; could you document it so I can make a decision without having to (potentially erroneously :p) read code?

Thanks!

**Comment by illfelder** [comment]
Thanks for the reminder! The documentation should be added in #330.

**Comment by illfelder** [comment]
Merged the pull request. Documentation should be up to date.
