### ISSUE TITLE
startup-scripts don't seem to work for Ubuntu 16.04 image

### ISSUE THREAD

**Issue by rohanrao91** [GoogleCloudPlatform/compute-image-packages#342]
Version: ubuntu-1604-xenial-v20160922
Tried using the startup-script option as well as via Google Storage.

**Comment by illfelder** [comment]
/cc @OddBloke 

Thanks for the report - this appears to be an issue with the latest image release. As we work with Canonical to fix the issue, I'd suggest using the ubuntu-1604-xenial-v20160921 image.

**Comment by illfelder** [comment]
The problematic image is rolled back so the issue should be (mostly) resolved.

**Comment by TomTasche** [comment]
Hey there,

Unfortunately this doesn't seem to be resolved (or I'm experiencing a similar issue). Here's my bug report on the old / other bug tracker: https://code.google.com/p/google-compute-engine/issues/detail?id=426

PS: I was able to reproduce the problem today. @illfelder

**Comment by TomTasche** [comment]
Oh I see, the Cloud Console says "amd64 xenial image built on 2016-09-21" so that obviously does not include the fix you mentioned above. When are images expected to be updated in Cloud Console?

**Comment by illfelder** [comment]
The existing image that you are running should work out of the box, however the issue presents after updating packages. Canonical is pushing package updates to close off the issue (followed by new images).

**Comment by Kamforka** [comment]
Any update on this issue? One and a half year passed and it's still not working for me.

**Comment by OddBloke** [comment]
Hi @Kamforka, could you give us an example gcloud command line that reproduces the problem you are seeing?

**Comment by Kamforka** [comment]
Hi @OddBloke this is my way of doing things:

I've set up a metadata for my Ubuntu 16.04 LTS compute engine instance as:
key: startup-script 
value: 
```
#! /bin/bash
su my_user -c gcsfuse my-storage /home/Storage/
```

I restarted the VM, did ssh into in through the web console. And noted that  the mount command specified in the startup wasn't executed.

Also tried to execute the startup-script manually like:
`sudo google_metadata_script_runner --script-type startup`
But nothing happened.

**Comment by Kamforka** [comment]
@OddBloke 
Well it was my mistake, I used a different image that is not Ubuntu 16.04, but Debian stretch.
On the Ubuntu image it works fine, although I still don't understand why it does not on Debian?

**Comment by OddBloke** [comment]
@Kamforka I'd suggest opening a separate issue for that. :-)

@illfelder I think we can close this out now?

**Comment by illfelder** [comment]
When running manually, add the debug flag to your command so you can see the script output:
`sudo google_metadata_script_runner --script-type=startup --debug`

**Comment by flaviokr** [comment]
We are facing the same problem. We upgraded from Ubuntu 14.04 to Ubuntu 16.04 (with `apt-get dist-upgrade` command) and startup scripts stopped working after the upgrade. 

When we run manually the 14.04 version: `sudo /usr/share/google/run-startup-scripts
` it works

When we run manually the 16.04 version: `sudo google_metadata_script_runner --script-type=startup --debug` it returns `sudo: google_metadata_script_runner: command not found`

How to solve this?

**Comment by OddBloke** [comment]
@flaviokr Could you run `dpkg -l | grep '\(gce\|goog\)'` and paste the output here, please?

**Comment by flaviokr** [comment]
```
ii  gce-cloud-config                      1.2.2-0ubuntu2~14.10.0                      amd64        Configuration for Ubuntu on Google Compute Engine
ii  gce-daemon                            1.2.2-0ubuntu2~14.10.0                      amd64        Google daemon for configuring instances
ii  gce-imagebundle                       1.2.2-0ubuntu2~14.10.0                      amd64        Bundle image for use on Google Compute Engine
ii  gce-startup-scripts                   1.2.2-0ubuntu2~14.10.0                      amd64        Google Compute Engine Start-up scripts
ii  google-cloud-sdk                      0.9.37-20141125060859+dsf1-0ubuntu1~14.10.0 all          Google Cloud SDK for interacting with Google Cloud services.
ii  google-compute-engine-oslogin         20171129+dfsg1-0ubuntu1~16.04.0             amd64        Google Compute Engine OS Login
```

We installed `google-compute-engine-oslogin` recently while trying to fix this issue.

**Comment by illfelder** [comment]
It looks like your VM is running a very old version of the guest environment. It's possible you're running into an issue we fixed in a guest environment change that you haven't yet updated to. We have instructions on how to update here: https://cloud.google.com/compute/docs/instances/linux-guest-environment. Let me know if you run into any problems.

**Comment by jessequinn** [comment]
problem exists with ubuntu18

```
dpkg -l | grep '\(gce\|goog\)'
ii  google-compute-engine              20210629.00-0ubuntu1~18.04.0              all          Google Compute Engine guest environment.
ii  google-compute-engine-oslogin      20210728.00-0ubuntu1~18.04.0              amd64        Google Compute Engine OS Login
ii  google-guest-agent                 20210629.00-0ubuntu1~18.04.1              amd64        Google Compute Engine Guest Agent
ii  google-osconfig-agent              20210608.1-0ubuntu1~18.04.1               amd64        Google OS Config Agent

```
