### ISSUE TITLE
gce-compute-images-packages Ubuntu 16.04 LTS - Retrigger Startup Script

### ISSUE THREAD

**Issue by carlsmithmeuk** [GoogleCloudPlatform/compute-image-packages#376]
Recently been having issues on Ubuntu 16.04 LTS with GCE Startup Script

Script includes lines at the top of file 

```
apt-get update
apt-get upgrade -y # This causes the startup script to start for a second time and stops the original startup script running
```

When removing upgrade from script and running manually once server has booted through, run `apt-get upgrade -y` manually and when it gets to upgrading gce-compute-images-packages the GCE Startup script runs again.

**Comment by zmarano** [comment]
I will file a bug with Canonical on this- but I did find the issue. They are using a different postinst than we provide here in the package they provide for Ubuntu images.It starts the google-startup-script.service anytime the postinst runs on an update (which is obviously not the right behavior).

**Comment by zmarano** [comment]
There are new packages for Ubuntu which have resolved this update bug. You should no longer see this behavior on Ubuntu. Please let us know if you still do.
