### ISSUE TITLE
User home directory mode unsafe

### ISSUE THREAD

**Issue by ryancurrah** [GoogleCloudPlatform/compute-image-packages#382]
In the [google_compute_engine/accounts/accounts_utils.py](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/e843cc6919bbed8203ef8ce87b5a3120d4e86800/google_compute_engine/accounts/accounts_utils.py#L173-L174) file on lines 173-174. It sets insecure permissions of 755 on home directories which is failing our audit requirement for the [RHEL7 STIG](http://rhel7stig.readthedocs.io/en/latest/medium.html#rhel-07-020700-all-files-and-directories-contained-in-local-interactive-user-home-directories-must-have-mode-0750-or-less-permissive). Is the 755 permission required? Or can I make a PR setting it to something safer that will pass audits like 750?

**Comment by zmarano** [comment]
Sure that sounds like a reasonable change, go ahead and make a PR for that and also make sure you sign the [CLA](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/CONTRIB.md).

**Comment by ryancurrah** [comment]
Hi @zmarano thanks for the response. I have signed the CLA and created [PR 384](https://github.com/GoogleCloudPlatform/compute-image-packages/pull/384).

**Comment by ryancurrah** [comment]
My new PR https://github.com/GoogleCloudPlatform/compute-image-packages/pull/385 from the development branch was merged. Closing this issue.

**Comment by illfelder** [comment]
Based on feedback from another user (and rereading the code) I've opened up a new pull request #394 that will remove setting permissions on the home directory. The permissions should be determined from the umask and we shouldn't have to override them in the guest code.
