### ISSUE TITLE
Allow disabling overwriting existing directories and files ownership and permissions

### ISSUE THREAD

**Issue by gdubicki** [GoogleCloudPlatform/compute-image-packages#387]
~Accounts daemon interferes with our configuration management system, as they both create users with same names. If Accounts would be configurable with a prefix that would be added to the usernames it manages, the problem would be solved.~

UPDATE: After consideration I realized that there is other way to resolve my issue - add setting to allow disabling changing existing directories and files ownership and permission. Because THAT is what exactly our SCM is doing differently than Accounts daemon. If we disable it then everything will be fine.

I created an appropriate MR for that, leaving the current behaviour as default, of course.

**Comment by illfelder** [comment]
Setting a prefix on usernames added by the accounts daemon would break users trying to log in via SSH (since the username they are specifying the SSH request would be different from the name of the user account in the guest). It seems like you would be better off disabling the accounts daemon, which you can do by adding a `/etc/default/instance_config.cfg.template` file and specifying:

    [Daemons]
    accounts_daemon = false

You would also need to reload the daemon for the change to be picked up.

**Comment by gdubicki** [comment]
I have updated my initial comment and created a PR: https://github.com/GoogleCloudPlatform/compute-image-packages/pull/388

Can you please take a look at this issue again, @illfelder ?

**Comment by illfelder** [comment]
Thanks for the contribution, but I still don't understand what you are trying to accomplish. I'm looking over the change and I don't see why this is a configuration we should support in the guest. (It seems like it would add complexity without a clear use case).

**Comment by gdubicki** [comment]
We manage most users accounts and keys on GCE nodes with SCM. However we still find the Accounts daemon user and key management useful as it works even if our SCM fails and quickly creates the accounts for our admins.

So we want to keep both solutions.

But our SCM sets homes permissions to `700` (and we want to keep it that way) while Accounts changes it to other value. So each run of each solution they change those permissions back and forth. This generates a lot of noise.

**Comment by illfelder** [comment]
Thanks for the clarification. I discussed the issue with the team and I don't think this is a configuration we want to support. In general we want to enable as much guest configuration as is needed by users, but in order to prevent the code from becoming unwieldy, we want to avoid configurations that are specific to integrating the accounts daemon with other account management services.

**Comment by gdubicki** [comment]
I understand. I also thought about it and we can in fact deal with our issue by disabling Accounts daemon, as you initially suggested, with SCM. As once it kicks in it can take over accounts management completely and there will be no "competition" problem. Of course there are rare cases where SCM will break AND we will add users that we would want Accounts to create on the nodes, but we should fix the SCM then anyway.

**Comment by gdubicki** [comment]
One more thing @illfelder : why should I disable Accounts daemon with a config and leave it running instead of just stopping and disabling its system service?

**Comment by illfelder** [comment]
Disabling the daemon via the config will persist across package updates.

**Comment by gdubicki** [comment]
Thanks.

But my experience with changing the config was, to put it mildly, not very nice. First I blindly copied the path from your comment and it had a non-obvious typo - `instance_config` -> `instance_configs`. Then only after some time I found the comment in `/etc/default/instance_configs.cfg` that told me to run `/usr/lib/python2.7/site-packages/google_compute_engine/instance_setup/instance_config.pyc` to apply my changes. But in fact you have to run `/usr/lib/python2.7/site-packages/google_compute_engine/instance_setup/instance_setup.py` instead. This should be added to README...

**Comment by illfelder** [comment]
Very sorry about the incorrect file location in documentation. I made a pull request (#389) to fix the documentation in `instance_config.py`.

**Comment by illfelder** [comment]
I merged the documentation updates. Hopefully others won't experience the same trouble you run into. Let us know if you find any other issues.

**Comment by gdubicki** [comment]
It's much better now, thank you! :)
