### ISSUE TITLE
ICMP Secure Redirects and CIS7 Compliance

### ISSUE THREAD

**Issue by qvallance-ctc** [GoogleCloudPlatform/compute-image-packages#390]
Running into a compliance issue with a couple of the network kernel params being set for GCP images.

The the kernel networking parameters for allowing secure ICMP redirects, `net.ipv4.conf.all.secure_redirects` & `net.ipv4.conf.default.secure_redirects`, are being enabled on GCP RHEL7 images (lines 31-32, [`/sysctl/11-gce-network-security.conf`](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/e843cc6919bbed8203ef8ce87b5a3120d4e86800/google_config/sysctl/11-gce-network-security.conf#L31-L32)).   The Common Internet Security Benchmark for RHEL7 (CIS7) indicates they should be disabled (4.2.3 - pg. 67, [CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v1.0.0.pdf](https://benchmarks.cisecurity.org/tools2/linux/CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v1.0.0.pdf)).

Is there a specific reason why GCP need to allow ICMP redirects from secure gateways (i.e., is there any issue if we disable them for compliance)?

The rationale for disabling them, from the CIS7 benchmark:
> It is still possible for even known gateways to be compromised. Setting net.ipv4.conf.all.secure_redirects to 0 protects the system from routing table
updates by possibly compromised known gateways.

**Comment by mattatgoogle** [comment]
The secure_redirects sysctl is dependent on accept_redirects being set to 1.  If accept_redirects is set to 0, then the value of secure_redirects has no effect.

The reason Google sets secure_redirects to 1 (also the kernel default) is as an additional security measure in the event that accept_redirects is ever set to 1 (intentionally or not).  If accept_redirects is set to 1 and secure_redirects is set to 0, as described in the CIS7 benchmark, then users would be immediately susceptible to ICMP redirects from any host.  

In your case for compliance, as long as accept_redirects is set to 0, then you can set secure_redirects to any value you want, but Google recommends using the default of 1 as an additional protection.

**Comment by qvallance-ctc** [comment]
That works for me.  Thanks for the clarification.
