### ISSUE TITLE
google-compute-engine-init %post failure due to missing systemctl

### ISSUE THREAD

**Issue by simaishi** [GoogleCloudPlatform/compute-image-packages#392]
Creating a custom CentOS 7 image using kickstart and running into an issue with google-compute-engine-init post script. In my installation, when google-compute-engine-init is installed, systemd isn't installed yet. This causes %post to fail:

```
20:38:01,593 INFO packaging: google-compute-engine-init-2.1.2-0.1488484921.el7.x86_64 (284/602)
20:38:01,593 INFO packaging: /var/tmp/rpm-tmp.vp8krH: line 17: systemctl: command not found
20:38:01,593 INFO packaging: /var/tmp/rpm-tmp.vp8krH: line 18: systemctl: command not found
....
20:38:01,596 INFO packaging: warning: %post(google-compute-engine-init-2.1.2-0.1488484921.el7.x86_64) scriptlet failed, exit status 127
```

The packages are installed as follows:

```
20:38:01,593 INFO packaging: google-compute-engine-init-2.1.2-0.1488484921.el7.x86_64 (284/602)
....
20:38:01,620 INFO packaging: systemd-219-30.el7_3.7.x86_64 (412/602)
```

Can gogole-compute-engine-init RPM 'require' systemd so the packages are installed in order?

**Comment by zmarano** [comment]
This issue should be resolved as of the latest release and new spec files.

https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/specs/google-compute-engine.spec
