### ISSUE TITLE
google_accounts_daemon should not change permissions on home directories

### ISSUE THREAD

**Issue by ebiggers** [GoogleCloudPlatform/compute-image-packages#393]
Following https://github.com/GoogleCloudPlatform/compute-image-packages/pull/385, google_accounts_daemon is setting home directories to mode 0750 when it installs public keys to ~/.ssh/authorized_keys.  This causes problems if users have intentionally set home directories to have different permissions, e.g. world-readable.  This is an issue with [gce-xfstests](https://github.com/tytso/xfstests-bld/blob/master/Documentation/gce-xfstests.md), for example.  Probably google_accounts_daemon should not change the home directory's mode if it already exists.  (Changing the mode of ~/.ssh to 0700 should still be fine, though.)

**Comment by illfelder** [comment]
I've created a new pull request #394 to remove setting permissions on home directories. We should use the umask permissions automatically during useradd, and shouldn't have to override them.

**Comment by ryancurrah** [comment]
Nice! I thought about that but was not sure if there was a reason for it.

**Comment by illfelder** [comment]
Our initial reason for setting the permission on the home directory was (if I recall correctly) to ensure the SELinux context was set properly. Based on our current understanding, I don't believe that should be necessary. We'll build some images off of this change and verify the images work properly before we publish the changes. This may take a few weeks to reach production.

**Comment by illfelder** [comment]
New images are released with this fix.
