### ISSUE TITLE
stretch image using eth instead of ens

### ISSUE THREAD

**Issue by hentisemmle** [GoogleCloudPlatform/compute-image-packages#407]
I created a test instance using https://wiki.debian.org/Cloud/GoogleComputeEngineImage, specifically :
`gcloud compute instances create my-test-machine --image-project debian-cloud-testing --image-family debian-9`
The created image has interface on eth+ instead of en+ 
```
root@debian-9:/var/log# cat /etc/debian_version 
9.0
root@debian-9:/var/log# udevadm info /sys/class/net/eth0
P: /devices/pci0000:00/0000:00:04.0/virtio1/net/eth0
E: DEVPATH=/devices/pci0000:00/0000:00:04.0/virtio1/net/eth0
E: ID_BUS=pci
E: ID_MODEL_FROM_DATABASE=Virtio network device
E: ID_MODEL_ID=0x1000
E: ID_NET_DRIVER=virtio_net
E: ID_NET_LINK_FILE=/lib/systemd/network/99-default.link
E: ID_NET_NAME_MAC=enx42010af00002
E: ID_NET_NAME_PATH=enp0s4
E: ID_NET_NAME_SLOT=ens4
E: ID_PATH=pci-0000:00:04.0
E: ID_PATH_TAG=pci-0000_00_04_0
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Red Hat, Inc
E: ID_VENDOR_ID=0x1af4
E: IFINDEX=2
E: INTERFACE=eth0
E: SUBSYSTEM=net
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eth0
E: TAGS=:systemd:
E: USEC_INITIALIZED=1790108
E: net.ifnames=0
```

The message in /usr/share/doc/udev/NEWS.Debian.gz seems to indicate this is incorrect.

**Comment by zmarano** [comment]
Thanks for the heads up. We use [bootstrap-vz](https://github.com/andsens/bootstrap-vz) to build Debian images. Therefore the issue is there if its part of the build. I did find [this issue](https://github.com/andsens/bootstrap-vz/issues/245) on the subject from 2015. Do you know where the decision was made to switch to predictable network interface names in Debian? The only [thread](https://lists.debian.org/debian-devel/2015/05/msg00170.html) I can find suggests it was left as opt-in.

I'm on board with switching Stretch to use predictable network naming as long as that is sanctioned by the Debian community.

**Comment by hentisemmle** [comment]
Hi @zmarano 

The NEWS.Debian.gz file states that the old mechanism is deprecated and will be removed in Debian 10. The README referenced in the NEWS file confirms this with 

> This old schema is deprecated in Debian 9 ("Stretch"), and will not
> be supported any more in Debian 10.

The issue in bootstrap-vz also seems to add support for stretch by disabling the naming schema. The last comment on the issue does however also state: 

> Yup, closing. #276 fixed this, though currently we deviate quite a bit from standard Debian on this

Which seems to indicate this is something that should be fixed to be in line with Debian community.

The default provided ISO installation of stretch uses the new naming scheme, would this not indicate community sanctioning ?

Lastly, Strecth will be official on the 17th June, so people will start to expect an official image in line with release version. 

https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html

**Comment by zmarano** [comment]
Thanks, I'll ping the debian-cloud group and get their input. The other side of this coin is if Debian is using systemd-networkd instead of ifup scripts which require hard coded network devices. bootstrap-vz doesn't currently handle this correctly and I am not yet certain where that problem lies.

**Comment by zmarano** [comment]
The current thinking from the Debian cloud team is to leave Stretch as eth0 by using net.ifnames=0 (which is what bootstrap-vz already does). There isn't yet a good solution to solve the problems of virtual network devices changing or moving from underneath you (which is entirely possible in a cloud environment). See this bug for details:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863385

**Comment by hentisemmle** [comment]
Hi @zmarano 

Thanks for heads up. 

H
