### ISSUE TITLE
Consider tagging releases with their version instead

### ISSUE THREAD

**Issue by bsiegert** [GoogleCloudPlatform/compute-image-packages#414]
The last stable release (20170523) used a `version` string of 2.3.7. 

To be more in line with how most open source projects release stuff, I suggest that you use the version as the tag for your releases in the future. That is, the next release could be tagged `v2.4.0` instead of the release date.

**Comment by illfelder** [comment]
A GitHub release currently includes three packages, each with their own versioning. The release description includes information about which packages are updated, but there is no single version (other than date) that makes sense as the release title.
