### ISSUE TITLE
Impossible to install rpm package under the Packer

### ISSUE THREAD

**Issue by tyzhnenko** [GoogleCloudPlatform/compute-image-packages#426]
When I tried to prepare own image with the Packer I've tried to install pakages _google-compute-engine_, _google-compute-engine-init_, _google-config_ and while installation the config script from _google-compute-engine_ package [1] trying to reach metadata service and going into infinite loop.

1 - /usr/bin/google_instance_setup

**Comment by zmarano** [comment]
This issue should be resolved as of the latest release.

Instance setup is now only run on package upgrades- not install.
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/specs/google-compute-engine.spec
