### ISSUE TITLE
google-accounts-daemon error "Full path required for exclude: net:" when running Docker containers

### ISSUE THREAD

**Issue by craigafinch** [GoogleCloudPlatform/compute-image-packages#444]
google-accounts-daemon fills the system log with error messages on two CentOS 7 VMs. The only factor in common between these systems is that both are running Docker. My other CentOS 7 instances do not have this problem. When no Docker containers are running, no error messages are recorded. As soon as I use docker-compose to start containers, these error messages start to occur in the logs. There is always a group of 4 such messages together-it is probably not a coincidence that I am running 4 containers.

```
[root@instance-01 ~]$ systemctl status google-accounts-daemon.service
● google-accounts-daemon.service - Google Compute Engine Accounts Daemon
   Loaded: loaded (/usr/lib/systemd/system/google-accounts-daemon.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-07-24 23:37:10 UTC; 11min ago
 Main PID: 27359 (google_accounts)
   CGroup: /system.slice/google-accounts-daemon.service
           └─27359 /usr/bin/python /usr/bin/google_accounts_daemon

Jul 24 23:44:20instance-01 google_accounts_daemon[27359]: Full path required for exclude: net:[4026532310].
Jul 24 23:44:20 instance-01 google_accounts_daemon[27359]: Full path required for exclude: net:[4026532376].
Jul 24 23:45:46 instance-01 google_accounts_daemon[27359]: Full path required for exclude: net:[4026532180].
```

This behavior has also been reported here: https://stackoverflow.com/questions/45156390/google-accounts-daemon1140-full-path-required-for-exclude-net4026532634

Can you please disable these messages to keep noise out of the log files?

**Comment by illfelder** [comment]
The messages are not generated by the guest environment - they are SELinux messages specific to [installing Docker](http://egonzalez.org/tag/centos/) on CentOS.

**Comment by craigafinch** [comment]
@illfelder Thank you for the quick response. I agree that the messages are somehow related to SELinux, despite the fact that they are not logged in `/var/log/audit/audit.log` and are not found with `ausearch`.  The root cause may be an SELinux policy issue, but I'm hoping you can point me in the right direction to find it.

This message isn't specific to installing Docker, as other SELinux issues can trigger that message (https://unix.stackexchange.com/questions/293317/selinux-issue-full-path-required-for-exclude-net4026532292) I am seeing four of these messages in the logs every two minutes, as long as the containers are running, as opposed to only seeing them when Docker was installed.

Why are they logged as if they are coming from google-account-daemon? Is google-account-daemon doing something every two minutes to trigger these notices?

**Comment by illfelder** [comment]
The accounts daemon is activated every ~90 seconds to ensure that expired SSH keys are removed from the guest. At that time, the guest will attempt to create/update/remove users based on the non-expired keys in metadata. If some user isn't getting set up properly (maybe there is a problem adding the user to one of the listed groups?) it might result in something getting called every couple minutes.

Here is the function that gets called if you wanted to dig in:
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_compute_engine/accounts/accounts_daemon.py#L202

**Comment by illfelder** [comment]
Is there any action still needed here, or is it safe to close off this issue?

**Comment by craigafinch** [comment]
@illfelder The spurious log messages stopped with the recent release of CentOS 7.4, so no action is required.
