### ISSUE TITLE
Provide ifup and ifdown hook to google-network-setup.service

### ISSUE THREAD

**Issue by thyj** [GoogleCloudPlatform/compute-image-packages#475]
`google-network-setup.service` brings up and configures NICs on VM. Customer may want to configure policy routing for VM with multiple NICs [1]. However, it's hard to make policy routing configuration persistent:

1. There's no ifup or ifdown hook to `google-network-setup.service`. Adding policy routing configuration command to `/etc/rc.local` won't make it survive an OS restart if `google-network-setup.service` actually runs after rc.local. See [2] for an example.

2. Policy routing configuration will be lost after 'systemctl restart google-network-setup.service'. See [3] for example.

RHEL/CentOS can define routing policy in `/etc/syconfig/network-scripts/route-ethN`. Ideally, google-network-setup.service should support similar ifup or ifdown hook to make the configuration persistent.

[1] https://cloud.google.com/compute/docs/create-use-multiple-interfaces#configuring_policy_routing

[2]
```
[root@ws2 ~]# tail -3 /etc/rc.local 
ip route add 10.128.144.0/20 via 10.128.208.1 dev eth1
ip route add 10.138.176.0/20 via 10.128.208.1 dev eth1
ip route add 10.142.192.0/20 via 10.128.208.1 dev eth1
[root@ws2 ~]# 
```
```
[root@ws2 ~]# grep -E 'rc.local|network-setup' /var/log/messages
Sep  5 23:15:51 ws2 systemd: Starting /etc/rc.d/rc.local Compatibility...
Sep  5 23:15:51 ws2 rc.local: Tue Sep  5 23:15:51 UTC 2017
Sep  5 23:15:51 ws2 rc.local: RTNETLINK answers: Network is unreachable
Sep  5 23:15:51 ws2 rc.local: RTNETLINK answers: Network is unreachable
Sep  5 23:15:51 ws2 rc.local: RTNETLINK answers: Network is unreachable
Sep  5 23:15:51 ws2 rc.local: Tue Sep  5 23:15:51 UTC 2017
Sep  5 23:15:51 ws2 systemd: Started /etc/rc.d/rc.local Compatibility.
Sep  5 23:15:53 ws2 network-setup: INFO Enabling the Ethernet interfaces ['eth0', 'eth1'].
[root@ws2 ~]# 
```

[3]
```
[root@ws2 ~]# ip route add 10.128.144.0/20 via 10.128.208.1 dev eth1
[root@ws2 ~]# ip route add 10.138.176.0/20 via 10.128.208.1 dev eth1
[root@ws2 ~]# ip route add 10.142.192.0/20 via 10.128.208.1 dev eth1
[root@ws2 ~]# ip route | grep eth1
10.128.144.0/20 via 10.128.208.1 dev eth1 
10.128.208.0/20 via 10.128.208.1 dev eth1  proto static 
10.128.208.1 dev eth1  scope link 
10.138.176.0/20 via 10.128.208.1 dev eth1 
10.142.192.0/20 via 10.128.208.1 dev eth1 
[root@ws2 ~]# systemctl restart google-network-setup.service
[root@ws2 ~]# ip route | grep eth1
10.128.208.0/20 via 10.128.208.1 dev eth1  proto static 
10.128.208.1 dev eth1  scope link 
[root@ws2 ~]# 
```

**Comment by illfelder** [comment]
Apologies for not replying to this issue sooner. 

We enable this behavior as part of the configuration for the network setup daemon. We have some documentation in our [README](https://github.com/GoogleCloudPlatform/compute-image-packages#configuration) you may find helpful.

In a user config template file, you can specify a hook script to call in place of our network setup logic:

```
/etc/default/instance_configs.cfg.template
[NetworkInterfaces]
dhclient_script = {YOUR_DHCLIENT_HOOK_SCRIPT}
```

Alternatively, you can disable the network setup daemon from running at all and do everything yourself using the config options:
```
[NetworkInterfaces]
setup = false
```

If you don't want to write your own script, but need to call a different DHCP client, you can use:
```
[NetworkInterfaces]
dhcp_command = {YOUR_DHCP_CMD}
```

If you end up writing your own script, you may find it helpful to refer to the existing [network setup logic](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_compute_engine/network_utils.py) we currently use.

**Comment by aaarel** [comment]
Hi  illfelder, 
the link to: "**network setup logic we currently use**" is broken (404)

**Comment by illfelder** [comment]
Updated the links.

**Comment by jeffmccune** [comment]
FYI, the `dhclient_script` setting has no effect on EL7.  I notice the variable isn't referenced in `EnableNetworkInterfaces` in [el_7/utils.py](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/e6eab0c12df9192208233b31d8e2ac7e79cba44c/packages/python-google-compute-engine/google_compute_engine/distro_lib/el_7/utils.py#L53)
