### ISSUE TITLE
Create udev rule for nvme disks to /dev/disk/by-id symlinks

### ISSUE THREAD

**Issue by davidz627** [GoogleCloudPlatform/compute-image-packages#485]
A rule needs to be created so that uniquely identifiable symlinks are created for all attached nvme storage devices. This is necessary for us to enable nvme local ssd storage for users.

Maybe added to this file:
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/development/google_config/udev/65-gce-disk-naming.rules

**Comment by anilyigitfiliz** [comment]
#580

**Comment by davidz627** [comment]
PR that fixes this is merged.
