### ISSUE TITLE
instance_setup should generate SSH host keys when none are present

### ISSUE THREAD

**Issue by jkaplowitz** [GoogleCloudPlatform/compute-image-packages#504]
Right now, instance_setup does not correctly handle the case where no SSH host keys are present, failing to generate them and preventing SSH from starting.

Instead, when instance_setup triggers a key (re)generation, it could work this way:

1. If instance_config specifies a list of cipher suites for which to generate host keys, generate that list.
1. Otherwise, if any host keys are present on the system, generate that list.
1. Otherwise, unconditionally generate ed25519, ecdsa, and rsa host keys. Don't generate dsa keys in this case, as they're no longer viewed as secure; for example, Debian 9 no longer generates these keys upon a fresh install.

In terms of evaluating success vs failure, a success would be "at least one freshly generated host key is created, and no pre-existing host key remains on the system." If no host keys end up on the disk, it willl be impossible to log in, and if any old host keys remain present, there may be a security issue.

I suggest logging a non-blocking debugging message if any attempted cipher types fail to generate, but this is not inherently a problem by itself.

**Comment by illfelder** [comment]
A fix is merged into development. The change should make it into our next release if all goes well.

**Comment by illfelder** [comment]
We released this change a while back. Closing off the issue.
