### ISSUE TITLE
NTP client flexibility: please loosen Depends field for google-compute-engine deb

### ISSUE THREAD

**Issue by jkaplowitz** [GoogleCloudPlatform/compute-image-packages#505]
GCE best practice requires that VMs sync time via NTP to metadata.google.internal, but doesn't inherently require the particular NTP software in the "ntp" pacakge. Debian ships three NTP clients, and https://lwn.net/Articles/735211/ indicates that the more lightweight option chrony is the most secure.

Therefore, it would be great if you could loosen the mention of "ntp" in the google-compute-engine Depends line to indicate "chrony | ntp | time-daemon" instead. This should allow all available options to work, keeping whichever one is already installed upon upgrades, and preferring chrony if none are installed.

Thanks!

**Comment by zmarano** [comment]
Fixed in #503
