### ISSUE TITLE
Remove need to specify full disk in 

### ISSUE THREAD

**Issue by ivanistheone** [GoogleCloudPlatform/compute-image-packages#51]
Reading the docs,
https://developers.google.com/compute/docs/disks#formatting
I assumed that `<disk-name>` meant the short name "media1" in my case.

But this failed:

    /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" media1 /mnt/media1

Only when I put the full path to a device node in /dev did it work:

    /usr/share/google/safe_format_and_mount -m "mkfs.ext4 -F" /dev/disk/by-id/google-media1 /mnt/media1

Please be more clear with the docs.

**Comment by canausa** [comment]
I think this one can be closed based on the docs.

https://cloud.google.com/compute/docs/disks/persistent-disks#formatting

**Comment by canausa** [comment]
The docs seem to have been updated to be more clear? 

https://cloud.google.com/compute/docs/disks/persistent-disks#formatting

is this still a valid use case?
