### ISSUE TITLE
Relation between account_daemon and oslogin tools

### ISSUE THREAD

**Issue by ilya-kolpakov** [GoogleCloudPlatform/compute-image-packages#513]
I am using [NixOS](https://nixos.org/) on GCE and am looking into integrating authorization/authentication features. I see a certain redundancy in the provided features and I would like to confirm that my conceptual understanding is correct. Could you please tell me if I understand it correctly that

1. `google_authorized_keys` executable, `pam_oslogin_{login,admin}.so` modules and `nss_oslogin` modules always query the metadata server and do not rely in any way on `google_accounts_daemon`.
2. the primary goal of `google_accounts_daemon` is to keep the system database of users/accounts (`/etc/passwd`) in sync with the metadata server (rather than to merely keep a local copy of user/account/rights from the metadata server).

I see that the provided set of tools provides a lot flexibility. What I do not quite understand is the motivation to duplicate/maintain GCE user accounts in the standard UNIX user/group database. The alternative I have in mind is that the GCE daemon
1. maintains GCE accounts in sync with the metadata server
2. exposes them via PAM modules which consumers are configured to use

With this design GCE and system accounts never mix so that if something fails it is easier to identify what went wrong. The priority of different authentication methods also becomes more transparent as it is explicit in the configuration files of PAM consumers.

One big difference in comparison with the existing design (if I understand it correctly) is that deployment would require to reconfigure all the relevant PAM consumers to use GCE modules. I don't see it as disadvantage as the resulting permissions would arguably become much more transparent to the user.

**Comment by illfelder** [comment]
Your understanding seems mostly correct. I'll describe the OS Login feature, and then the relationship between the two account management mechanisms in the guest environment.

OS Login is a new beta feature that simplifies SSH key management and moves VM access management into IAM. You can read the [public documentation](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#oslogin) for how to use the feature. Here's a quick description of feature offerings:

Tight binding between ssh keys and user identities 
- SSH keys are tied to the user identity and not stored in VM metadata.
- SSH access lifecycle tied to user account lifecycle.
- Auditability; consistent usernames and UIDs across the organization (and project).

Authorization using IAM
- Separate SSH permissions for sudo vs non-sudo access.

Overcomes limitations with metadata ssh keys
- Project editor has access to set keys for any user.
- Limitations on number of keys that can be set in metadata.
- Metadata users always have sudo access in the guest.

Relationship: the accounts daemon is responsible for enabling and disabling OS Login. When OS Login is enabled, metadata based SSH key login is disabled and the accounts daemon is only responsible for watching the `enable-oslogin` key in metadata.

Please let me know if you have any other questions not answered by the public documentation (or my description here).

**Comment by ilya-kolpakov** [comment]
Many thanks for the detailed answer (better late than never).
