### ISSUE TITLE
oslogin: rpm post script causes a page fault on semodule

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-packages#515]
In the post install script from the google-compute-engine-oslogin rpm package, the following command causes a page fault:
    `semodule -i /usr/share/selinux/packages/oslogin.pp`

I am reproducing this using Daisy tool to translate an image of a Centos 6.8. When installing the package google-compute-engine in the libguestfs environment I get this non fatal error, the problem is that it breaks the libaudit.so.1 links and some labels in the fs and make the user unable to login in the machine from this translated image.

Logs: https://pastebin.com/raw/xL3cWXVB

**Comment by zmarano** [comment]
Do you know what machine type you were using? It looks like it ran out of memory.

**Comment by helen-fornazier** [comment]
n1-standard-2

**Comment by zmarano** [comment]
Can you try on an n1-standard-4 and see if you get the same results?

**Comment by helen-fornazier** [comment]
I got the same result, but it was weird that the same amount of pages were being reported in the log.
I just found that the libguestfs limits the memory to 500MB by default, I increased it to 4GB and now it works, this must be the same issue with the sdk.
Closing this

**Comment by helen-fornazier** [comment]
I don't get the pagefault anymore but it seems installing google-compute-engine package breaks libaudit.so.1 symlink (but this is another bug), I'll investigate a bit more
