### ISSUE TITLE
Create a directory in the Python package for distro-specific patches

### ISSUE THREAD

**Issue by illfelder** [GoogleCloudPlatform/compute-image-packages#516]
We can use this directory to clean up network setup logic, and enable Linux image distributions to have their patches maintained upstream.

**Comment by illfelder** [comment]
@helen-fornazier This will give BSD patches a home.

**Comment by helen-fornazier** [comment]
This would be great, I'll study how we can include this in a clean way.

**Comment by illfelder** [comment]
We made this update and it's currently part of our development branch. Closing the issue.
