### ISSUE TITLE
Instance under the Packer can't shutdown gracefully due the meta server absentee

### ISSUE THREAD

**Issue by tyzhnenko** [GoogleCloudPlatform/compute-image-packages#517]
While create image for GCE, the Packer can't shutdown VM because the shutdown script stucks in an infinity loop
```
 # /usr/bin/google_metadata_script_runner --script-type shutdown --debug
shutdown-script: INFO Starting shutdown scripts.
shutdown-script: ERROR GET request error retrieving metadata. <urlopen error [Errno -2] Name or service not known>.

```
Actual for - google-compute-engine-2.7.1-1.el6.noarch

**Comment by illfelder** [comment]
The guest environment is only intended to run on GCE VMs with access to the metadata server. Startup and shutdown scripts intentionally wait for access to the metadata server to ensure proper configuration and cleanup take place. If you do not have access to the metadata server and want to shutdown your instance, you can either disable shutdown scripts or stop the VM from the API layer (which will automatically shut the VM down after 2 minutes).
