### ISSUE TITLE
question: version number clarification

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-packages#533]
Hi,

There is a currently discussion going on in the FreeBSD community about which version number should be used for the google-compute-engine-oslogin package. The current question is if we should use the git tag as the FreeBSD port version or the MAJOR/MINOR/REVISION from the oslogin Makefile.
 
Please see discussion at https://reviews.freebsd.org/D13811#inline-83526

Could you please clarify the meaning of the git tags? And which version do you think we should use for the FreeBSD oslogin package please?

Thanks

**Comment by illfelder** [comment]
A GitHub release includes different packages, each with their own versioning. An update to one package shouldn't require version bumps in unaffected packages. The release tag is not the package version number; it just allows you to pull the latest code published on a certain date. The OS Login Makefile contains the package version I think you should use.

**Comment by helen-fornazier** [comment]
Thanks for the clarification.
google-compute-engine-oslogin was accepted and commited to the FreeBSD ports tree, closing this ticket.
