### ISSUE TITLE
OS Login & SSHd "Match" option

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/compute-image-packages#550]
Hi,
if the file sshd_config ends with a "Match" option, the two options added by "google_oslogin_control" are valid only for the matched accounts.

I suggest to modify the lines added from these:

```
# Added by Google Compute Engine OS Login.
AuthorizedKeysCommand /usr/bin/google_authorized_keys
# Added by Google Compute Engine OS Login.
AuthorizedKeysCommandUser root
```
to these:

```
# Added by Google Compute Engine OS Login.
Match all
# Added by Google Compute Engine OS Login.
AuthorizedKeysCommand /usr/bin/google_authorized_keys
# Added by Google Compute Engine OS Login.
AuthorizedKeysCommandUser root
```

**Comment by hopkiw** [comment]
we have resolved this potential error case in the new guest environment, expected later this year. instead of using match blocks, we simply moved the google configurations to the top of the file in a single block. this allows users to continue to flexibly override if they so choose.
