### ISSUE TITLE
Archive files location

### ISSUE THREAD

**Issue by arnrob14344** [GoogleCloudPlatform/compute-image-packages#555]
Hello,

Where can i find the latest and archive previous files location? I would like to use it for package management. Thank you.

**Comment by zmarano** [comment]
You can use any given [release](https://github.com/GoogleCloudPlatform/compute-image-packages/releases) which has a snapshot of the code at that time. Is this what you asking for?

**Comment by arnrob14344** [comment]
Yes. Thank you for the time helping.
