### ISSUE TITLE
sles11: enable-oslogin=true causes "Permission denied" for SSH

### ISSUE THREAD

**Issue by helen-fornazier** [GoogleCloudPlatform/compute-image-packages#581]
How to reproduce:

Make sure enable-oslogin is not defined in instance and project level.
Create an instance for Suse 11 (sles-11-sp4-v20180104)
Verify that you can login successfully with `gcloud compute ssh instance`
Set enable-oslogin=true in the instance
When trying to login again with `gcloud compute ssh instance`, it fails with `Permission denied (publickey).`

Message in the logs:

```
...
Restarting sshd.
Shutting down the listening SSH daemon                                done
Checking for missing server keys in /etc/ssh
Starting SSH daemon                                                   done
no crontab for user1
no crontab for user2
no crontab for root
userdel: Cannot determine your user name.
userdel: Cannot determine your user name.
```

**Comment by illfelder** [comment]
Thanks for the report - you're correct that OS Login does not work properly on SLES 11. We have that information documented, so no need to add OS Login testing for SLES 11:
https://cloud.google.com/compute/docs/instances/managing-instance-access#enable_oslogin
