### ISSUE TITLE
syslog-ng incompatibility Centos7

### ISSUE THREAD

**Issue by tu144** [GoogleCloudPlatform/compute-image-packages#583]
Hi, can't install syslog-ng on google cloud using Centos7 image as google-compute-engine requires rsyslog:

Resolving Dependencies
--> Running transaction check
---> Package rsyslog.x86_64 0:8.24.0-12.el7 will be obsoleted
--> Processing Dependency: rsyslog for package: google-compute-engine-2.7.6-1.el7.noarch
---> Package si-syslog.x86_64 0:1.0-11.el6 will be obsoleting
--> Processing Dependency: syslog-ng for package: si-syslog-1.0-11.el6.x86_64
--> Running transaction check
---> Package rsyslog.x86_64 0:8.24.0-12.el7 will be obsoleted
--> Processing Dependency: rsyslog for package: google-compute-engine-2.7.6-1.el7.noarch
---> Package syslog-ng.x86_64 0:3.5.6-3.el7 will be installed
--> Processing Dependency: ivykis >= 0.36.1 for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libivykis.so.0(IVYKIS_0.29)(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libivykis.so.0(IVYKIS_0.30)(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libevtlog.so.0()(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libivykis.so.0()(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libnet.so.1()(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Running transaction check
---> Package eventlog.x86_64 0:0.2.13-4.el7 will be installed
---> Package ivykis.x86_64 0:0.36.2-2.el7 will be installed
---> Package libnet.x86_64 0:1.1.6-7.el7 will be installed
---> Package rsyslog.x86_64 0:8.24.0-12.el7 will be obsoleted
--> Processing Dependency: rsyslog for package: google-compute-engine-2.7.6-1.el7.noarch
--> Finished Dependency Resolution
Error: Package: google-compute-engine-2.7.6-1.el7.noarch (@google-cloud-compute)
           Requires: rsyslog
           Removing: rsyslog-8.24.0-12.el7.x86_64 (@anaconda)
               rsyslog = 8.24.0-12.el7
           Obsoleted By: si-syslog-1.0-11.el6.x86_64 (local)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
ERROR: Yum operation 'Upgrading installed RPMs' failed!

**Comment by zmarano** [comment]
I haven't been able to reproduce this issue yet, and actually syslog-ng installs just fine on a default CentOS 7 GCE VM.

`[root@c7 ~]# yum install syslog-ng
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo1.sea.innoscale.net
 * epel: mirrors.cat.pdx.edu
 * extras: mirror.sjc02.svwh.net
 * updates: mirrors.sonic.net
Resolving Dependencies
--> Running transaction check
---> Package syslog-ng.x86_64 0:3.5.6-3.el7 will be installed
--> Processing Dependency: ivykis >= 0.36.1 for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libivykis.so.0(IVYKIS_0.29)(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libivykis.so.0(IVYKIS_0.30)(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libevtlog.so.0()(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libivykis.so.0()(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Processing Dependency: libnet.so.1()(64bit) for package: syslog-ng-3.5.6-3.el7.x86_64
--> Running transaction check
---> Package eventlog.x86_64 0:0.2.13-4.el7 will be installed
---> Package ivykis.x86_64 0:0.36.2-2.el7 will be installed
---> Package libnet.x86_64 0:1.1.6-7.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================================================================================================
 Package                                    Arch                                    Version                                          Repository                             Size
=================================================================================================================================================================================
Installing:
 syslog-ng                                  x86_64                                  3.5.6-3.el7                                      epel                                  453 k
Installing for dependencies:
 eventlog                                   x86_64                                  0.2.13-4.el7                                     epel                                   19 k
 ivykis                                     x86_64                                  0.36.2-2.el7                                     epel                                   35 k
 libnet                                     x86_64                                  1.1.6-7.el7                                      base                                   59 k

Transaction Summary
=================================================================================================================================================================================
Install  1 Package (+3 Dependent packages)

Total download size: 567 k
Installed size: 1.8 M
Is this ok [y/d/N]: y
Downloading packages:
(1/4): libnet-1.1.6-7.el7.x86_64.rpm                                                                                                                      |  59 kB  00:00:00     
(2/4): eventlog-0.2.13-4.el7.x86_64.rpm                                                                                                                   |  19 kB  00:00:00     
(3/4): ivykis-0.36.2-2.el7.x86_64.rpm                                                                                                                     |  35 kB  00:00:00     
(4/4): syslog-ng-3.5.6-3.el7.x86_64.rpm                                                                                                                   | 453 kB  00:00:00     
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                            649 kB/s | 567 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : ivykis-0.36.2-2.el7.x86_64                                                                                                                                    1/4 
  Installing : eventlog-0.2.13-4.el7.x86_64                                                                                                                                  2/4 
  Installing : libnet-1.1.6-7.el7.x86_64                                                                                                                                     3/4 
  Installing : syslog-ng-3.5.6-3.el7.x86_64                                                                                                                                  4/4 
  Verifying  : libnet-1.1.6-7.el7.x86_64                                                                                                                                     1/4 
  Verifying  : eventlog-0.2.13-4.el7.x86_64                                                                                                                                  2/4 
  Verifying  : ivykis-0.36.2-2.el7.x86_64                                                                                                                                    3/4 
  Verifying  : syslog-ng-3.5.6-3.el7.x86_64                                                                                                                                  4/4 

Installed:
  syslog-ng.x86_64 0:3.5.6-3.el7                                                                                                                                                 

Dependency Installed:
  eventlog.x86_64 0:0.2.13-4.el7                              ivykis.x86_64 0:0.36.2-2.el7                              libnet.x86_64 0:1.1.6-7.el7                             

Complete!
`

**Comment by illfelder** [comment]
@tu144 - are you still running into this problem? If so, can you provide additional information for reproducing the issue?

**Comment by sfuerte** [comment]
need to enable EPEL repo as per this doc - https://www.syslog-ng.com/community/b/blog/posts/installing-latest-syslog-ng-on-rhel-and-other-rpm-distributions

the subject package is part of that repo: 
https://centos.pkgs.org/7/epel-x86_64/ivykis-0.36.2-2.el7.x86_64.rpm.html
