### ISSUE TITLE
Updating Linux Guest Environment for Debian 7

### ISSUE THREAD

**Issue by hzyi-google** [GoogleCloudPlatform/compute-image-packages#585]
Hi,
This issue comes from the [documentation for installing linux guest environment](https://cloud.google.com/compute/docs/instances/linux-guest-environment). I started to receive notice saying I need to update the linux guest environment when I ssh into some GCE instances, yet there isn't instructions for debian 7. I tried to refer to the instructions for debian 8/9 but some resources is not found during the installation. Errors are listed below. Is there anything else I can do? Please let me know if I can provide more information.
Thanks in advance.
```
Err http://packages.cloud.google.com google-compute-engine-wheezy-stable/main amd64 Packages
...
Reading state information... Done
E: Unable to locate package python-google-compute-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-google-compute-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package google-compute-engine-oslogin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package google-compute-engine
```

**Comment by zmarano** [comment]
Debian 7 is EOL and we no longer maintain support for it in GCE. Our suggestion is to try to update to Debian 9 (current stable) or at least Debian 8.
