### ISSUE TITLE
google-network-daemon / google-ip-forwarding in systemd

### ISSUE THREAD

**Issue by mills95** [GoogleCloudPlatform/compute-image-packages#603]
The recent refactoring (2018) has caused some issues with knowing when the system has obtained the metadata and parsed the forwarding IPs. When google-ip-forwarding was a standalone daemon, we could wait for it to complete before starting processes that depend on having those IPs.  However, now that it is dynamically spawned, this is no longer possible.  Is there an option to force google-ip-forwarding to run before google-network-daemon returns so we can wait on that?
Right now, we have to put in a time delay which is both problematic and wasteful; we don't want to miss the completion, but we also want the server to start up as quickly as possible. But we have to have something that works if our instance is migrated.

**Comment by illfelder** [comment]
Thanks for the report! We found an issue where we introduced a ~2 minute delay when setting IP forwarding routes. We are actively working on a fix.

**Comment by illfelder** [comment]
The fix is merged, release, and included in the latest Debian, CentOS, and RHEL images.
