### ISSUE TITLE
Ubuntu public images have sshd_config's PermitRootLogin set to other than "no"

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-packages#604]
From [configuration integration test requirement](https://github.com/GoogleCloudPlatform/compute-image-tools/blame/master/daisy_workflows/image_test/README.md#L127):
```
Ensure sshd config has sane default settings:
- PermitRootLogin no
```
* **ubuntu 1604** has it as "prohibit-password", which still allows root login through public-key, hostbased and GSSAPI authentication. 
* **ubuntu 1404** has it as "without-password", which is just a [synonym for "prohibit-password"](https://www.openssh.com/txt/release-7.0). 
* **ubuntu 1710** and **ubuntu 1804** don't set one config, so it fallbacks to default "prohibit-password" according to documentation.

Was this a false positive? Should actually my test allow "prohibit-password" or are these ubuntu images faulty?

**Comment by gut** [comment]
@zmarano : ping. Is this real concern?

**Comment by zmarano** [comment]
I don't believe so but we can bring it up with Canonical.
