### ISSUE TITLE
debian-8 public image has its automatic updates disabled by default

### ISSUE THREAD

**Issue by gut** [GoogleCloudPlatform/compute-image-packages#607]
From [configuration integration test requirement](https://github.com/GoogleCloudPlatform/compute-image-tools/blame/master/daisy_workflows/image_test/README.md#L135):
```
-   Ensure automatic security updates are enabled per distro specs.
    -   Unattended upgrades for the Debian security repos, and apt
config is correct.
```

The unattended-upgrades service is disabled:
```
$ sudo service unattended-upgrades status
● unattended-upgrades.service - Unattended Upgrades
   Loaded: loaded (/lib/systemd/system/unattended-upgrades.service; enabled)
   Active: inactive (dead)
     Docs: man:unattended-upgrade(8)
```

And on debian-9 it looks fine:
```
$ sudo service unattended-upgrades status
● unattended-upgrades.service - Unattended Upgrades Shutdown
   Loaded: loaded (/lib/systemd/system/unattended-upgrades.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2018-05-11 14:20:37 UTC; 4min 51s ago
     Docs: man:unattended-upgrade(8)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/unattended-upgrades.service

May 11 14:20:37 gut-test systemd[1]: Started Unattended Upgrades Shutdown.
```

**Comment by zmarano** [comment]
It is enabled and working - at least in the VM's I am looking at (there are logs in /var/log/unattended-upgrades that can validate that). It is possible that the systemd service is reporting differently however. We use the [bootstrap-vz plugin](https://github.com/andsens/bootstrap-vz/blob/master/manifests/official/gce/jessie.yml#L54) to enable it for the security repo.

**Comment by gut** [comment]
You are right. I see activity there nevertheless... It looks like it's something that the new version of unattended-upgrades (found on debian-9) took care of.

I already test if unattended-upgrades package is installed and if there is some repository set to fetch upgrades from so I hope that these 2 verification are enough to validate that "automatic security updates are enabled per distro specs.", ok? I'll update GoogleCloudPlatform/compute-image-tools#404 accordingly then.
