### ISSUE TITLE
ubuntu-1804-lts startup script don't run

### ISSUE THREAD

**Issue by solidsystem** [GoogleCloudPlatform/compute-image-packages#614]
I'm having a problem getting startup script to run on ubuntu-1804-lts image.

To test I Have this script uploaded to a cloud storage bucket:

> #!/usr/bin/env bash
> 
> date >> /tmp/bootscript.log
> 

I then create the instance like this:
`gcloud compute instances create "client-ubuntu-1804" \
--zone="us-east1-c" \
--machine-type="f1-micro" \
--network="default" \
--image-family="ubuntu-1804-lts" \
--image-project="ubuntu-os-cloud" \
--boot-disk-size="20" \
--boot-disk-type="pd-standard" \
--boot-disk-auto-delete \
--scopes="cloud-platform" \
--service-account="xxx@<PROJECT-ID>.iam.gserviceaccount.com" \
--metadata startup-script-url="gs://<BUCKETNAME>/scripts/tryboot.sh"`

When I SSH into the instance there is no /tmp/bootscript.log file, so the script has clearly not run.

If I then run the startup script manually like  this:
`sudo google_metadata_script_runner --script-type=startup --debug`

It runs as expected and produce the expected output file.

Works as expected on ubuntu-1604-lts image.

Would be great to get a fix for this.

**Comment by zmarano** [comment]
This issue was fixed and is no longer a problem in current 18.04 images.
