### ISSUE TITLE
Docker image that we can use ?

### ISSUE THREAD

**Issue by sandys** [GoogleCloudPlatform/compute-image-packages#618]
hi guys,
I'm looking to deploy a whole bunch of docker images to Google Compute with a fair amount of customization.
One of the important things I'm looking to use is the ability to add and remove accounts (ssh keys) from the Google Cloud console. 

Do you guys have a Ubuntu/Debian Dockerfile that I can build upon ? I'm not able to figure out how to integrate google accounts daemon. Since systemd does not work on docker images, we usually use supervisord or use the baseimage-docker VM (https://hub.docker.com/r/phusion/baseimage/ and http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/)

Do you guys have any Docker images we can use ?

**Comment by sandys** [comment]
Hi Zach
Google cloud allows us to use a docker VM to create an instance ..instead
of the standard  images.

So this is something that you guys already do. But when I do this I lose
some of the nice abilities of the dashboard especially creating
accounts.which is why I filed this bug : can I run so.e of.your services
(like accounts service) inside a docker image instead of this VM recipe
that you have.

Intuitively, it ought to be possible.

I'm not sure why you mention entering a guest image. That is definitely not
my ask here.

**Comment by sandys** [comment]
hi zach,
thanks for replying.

we run fat Docker containers. Its not ideal, but works pretty great as a
quick debug option. But you will be interested to know, that in this
particular situation we are deploying it as a ssh bastion machine.
Something like this - https://github.com/zalando-stups/odd
This project pulls the ssh keys from a s3 url. It would have been cool to
leverage the google accountsmanager service to do the same.

**Comment by zmarano** [comment]
I see. That is an interesting use case but yeah its not the case for the GCE guest software in this repository which is meant for guest VM's (or container hosts in this case). The python library for google-compute-engine however is available as a deb and rpm package and a [pypi package](https://pypi.org/project/google-compute-engine/). You could use the same functionality and only use the accounts daemon from a container perhaps. But this wouldn't be a supported use case and I can't guarantee we wouldn't break that use case in the future.
