### ISSUE TITLE
unsafe usernames may reference other files

### ISSUE THREAD

**Issue by setharnold** [GoogleCloudPlatform/compute-image-packages#621]
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/3d67bc6271650c8e1fc19b8420c17f6e204d1272/google_compute_engine_oslogin/pam_module/pam_oslogin_admin.cc#L74

Hello,

I reviewed this package as part of the Ubuntu Main Inclusion Review process, and found a few small items I think should be addressed.

If the username includes sequences of `../` opening this file may have unexpected consequences. The metadata server will probably reject usernames of this style but I think this module should itself refuse to work on unexpected files regardless of the proper functioning of the metadata server.

Thanks

**Comment by flokli** [comment]
This can be closed, given #633 was merged.
