### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by Gabology** [GoogleCloudPlatform/compute-image-packages#625]
I can't find any documentation on how you run the binaries in debug mode. In the code there are various references to setting a debug flag to enable logging to the console, and the documentation also confirms this:

> The Google added daemons and scripts write to the serial port for added transparency. A common logging library is a thin wrapper around the Python logging module. The library configures appropriate SysLog handlers, sets the logging formatter, and provides a debug options for added logging and console output.

However nowhere can I find any reference as to how I enable debug logging when running the binaries directly.

**Comment by illfelder** [comment]
Apologies for the delay in replying to this. We do not currently have a way to enable debug mode once the binary is running. Debug mode can be specified when starting the binary by specifying the `--debug` flag. For example:
```
sudo /usr/bin/google_accounts_daemon --debug
```
Note that you can't run multiple instances of the same daemon at once.
