### ISSUE TITLE
Provide Fedora 27 RPM packages

### ISSUE THREAD

**Issue by vZ2JEZsZW** [GoogleCloudPlatform/compute-image-packages#627]
Any chance for Fedora 28 support?
Or it is just google decision to not support anything but standard images backed into gce? What the point of having these compute-image-packages then?
upd: sorry, I meant Fedora  **28**

**Comment by vZ2JEZsZW** [comment]
@illfelder 
>EL 7 RPMs that will likely work in Fedora

They don't. EL7 rpms  depend on some json c lib (something with api 11 in contrast to the current 13 one) that is not provided by Fedora 28. However one can rebuild EL7 json lib for Fedora (and gave it new name). But it does not helps: cloud compute packages installs but are not seem to work.

Also with help of zmarano I located the third SPEC file and build all three RPMS in Fedora (oslogin one  needed some adaptation though). They installs but don't work: no services at systemd appeared. Also an attempt to remove these packages with `dnf remove` caused error of rpm script, so you got package that you can't even get rid of. Or probably I just made something incorrectly while building.

Unfortunately I destroed all VMs (so I lost exact error messages so have to reproduce by memory) after a day of trying to adapt Fedora Cloud Base image to Google compute and adapting `compute-image-packages` rpms for Fedora. However I got to the point where it boots and acquires IP by means of DHCP and NetworkManager (the key was to ditch out cloud-init, and install NetworkManager back). So it works but as far as I understand VM can only reach its full potential with `compute-image-packages`.

Thank you anyway for assistance.

>will likely work in Fedora, but we don't use Fedora in our testing environments

You ether have prebuilt Fedora images available in google compute panel OR don't claim it will work.

(There is also third option - community images catalog, but can't find in google panel)

>we welcome pull requests to make any of our guest environment code more robust

Oh, no, unfortunately I am not world-class top engineer, sorry, above my paygrade.
And yes, there are better projects for volunteering than google's commercial product.

**Comment by illfelder** [comment]
Sorry to hear that it it does not work out of the box and that you're not interested in making a contribution. We don't publish that Fedora is supported operating system by the packaging we provide anywhere in our documentation, and don't haven't previous heard requests for it. We determine new features and prioritization based on user feedback, so if Fedora is important to your workload, please leave a [feature request](https://cloud.google.com/support/docs/issue-trackers#search_for_or_create_bugs_and_feature_requests_by_product) to help us gauge user interest.
