### ISSUE TITLE
source packages for rpm

### ISSUE THREAD

**Issue by vZ2JEZsZW** [GoogleCloudPlatform/compute-image-packages#628]
Where are source packages? Aren't they supposed to be somewhere in `https://packages.cloud.google.com/yum/repos/`? Can't find them.

```
[root@instance-2 ~]# dnf download --source --enablerepo=google-cloud-compute google-compute-engine
enabling updates-source repository
enabling fedora-source repository
Last metadata expiration check: 0:12:36 ago on Tue 17 Jul 2018 03:17:26 PM UTC.
No package google-compute-engine-2.8.3-1.el7.src available.
Exiting due to strict setting.
Error: No package google-compute-engine-2.8.3-1.el7.src available.
```

This is what `google-cloud.repo` contains. Got repo config from some official google documentation page:

```
[root@instance-2 ~]# cat /etc/yum.repos.d/google-cloud.repo 
[google-cloud-compute]
name=Google Cloud Compute
baseurl=https://packages.cloud.google.com/yum/repos/google-cloud-compute-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

**Comment by eklitzke** [comment]
+1, this would be very useful. Particularly for those of us running Fedora in Google Cloud who want to rebuild RPMs, as some of the RHEL binary packages don't install on Fedora.

**Comment by hopkiw** [comment]
We do upload source RPMs, apparently the issue is an internal bug preventing them from being properly downloaded. I'll keep this issue open as we track internally.
