### ISSUE TITLE
SPEC file for google-compute-engine-oslogin

### ISSUE THREAD

**Issue by vZ2JEZsZW** [GoogleCloudPlatform/compute-image-packages#629]
Can't find spec-file for `google-compute-engine-oslogin`. Should't it be in specs directory? Or `google-compute-engine-oslogin` is a product of some other spec-file?

**Comment by zmarano** [comment]
It is currently in its own directory (https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_compute_engine_oslogin/packaging/rpmbuild/SPECS/google-compute-engine-oslogin.spec)... we do need to migrate it and had plans to do so. I'll keep this issue open to track that.

**Comment by vZ2JEZsZW** [comment]
oh, thank you
