### ISSUE TITLE
Clock Skew Daemon doesn't sync time 

### ISSUE THREAD

**Issue by capsl0cker** [GoogleCloudPlatform/compute-image-packages#634]
I have one question about Clock Skew Daemon:
does it only sync time while starting/stopping/mirgrating VM instance?
i.e. for a running VM, if I change system time with command 'date -s xxx', will it correct time back?
From my experiments, it won't correct it. Is this a designed behavior?
If it is, my question is how to keep time sync with host in GCP if don't enable ntp?

**Comment by illfelder** [comment]
The Clock Skew Daemon is triggered by changes to a metadata key that is set during the events you listed. The purpose of the daemon to prevent platform functionality, not user-initiated changes. NTP will still correct your manual changes, but does not run frequently. We recommend not disabling the NTP service if you need it's functionality.
