### ISSUE TITLE
Startup-script doesn't work with python file

### ISSUE THREAD

**Issue by minhthehash** [GoogleCloudPlatform/compute-image-packages#654]
Hi all,  
I'm trying to create startup script in Compute Engine - in directly way when create VM instance, I want to run command just like in SSH command line. Here my startup script:
```
#!/bin/bash
sudo python3 /home/minhngc4795/test.py
```

Here is my test.py file, I want to write line "test" to test.txt file in folder:

```
#!/usr/bin/python3
file = open("test.txt","w")
file.write("test")
file.close()
```

When I start VM instance and check /var/log/syslog, it doesn't return error code or anything, just return 0

```
Sep  7 10:18:18 startupscript systemd[1]: Starting Google Compute Engine Startup Scripts...
Sep  7 10:18:18 startupscript startup-script: INFO Starting startup scripts.
Sep  7 10:18:18 startupscript startup-script: INFO Found startup-script in metadata.
Sep  7 10:18:18 startupscript startup-script: INFO startup-script: Return code 0.
Sep  7 10:18:18 startupscript startup-script: INFO Finished running startup scripts.
``` 

But nothing happens in my folder. I try to figure it out but nothing come up. Pls help me, thks a lot. 
I'm using Ubuntu 16.04.5 LTS

**Comment by zmarano** [comment]
Startup scripts can be python scripts or any other interpreter. I suggest you just use your test.py script as the startup script and don't try to call a script that may or may not exist.

**Comment by illfelder** [comment]
Startup scripts run as root, so you shouldn't be calling sudo. By calling sudo you are creating a new shell and your script likely won't run in the way you expect.

**Comment by illfelder** [comment]
If you log into a VM, you can test out your startup script by running the following command:

```
sudo /usr/bin/google_metadata_script_runner --script-type=startup --debug
```

**Comment by minhthehash** [comment]
Thks all, but nothing change. The output is still same, I used python code as startup and didn't use sudo.
Return from sudo /usr/bin/google_metadata_script_runner --script-type=startup --debug:
```
startupscript systemd[1]: Starting Google Compute Engine Startup Scripts...
startupscript startup-script: INFO Starting startup scripts.
startupscript startup-script: INFO Found startup-script in metadata.
startupscript startup-script: INFO startup-script: Return code 0.
```

**Comment by illfelder** [comment]
Thanks @gut! Closing this off.

**Comment by gut** [comment]
no problem. I hope this is exactly the problem @minhthehash . Please confirm if otherwise.

**Comment by gut** [comment]
Great! Have fun then.
