### ISSUE TITLE
Multiple nic problem

### ISSUE THREAD

**Issue by oscarr1605** [GoogleCloudPlatform/compute-image-packages#670]
Hi.

I've an instance with Centos 6 and multiple network interfaces, when the package is updated the networks fails, I need to restart to solve.

Is there a way to solve this?

**Comment by zmarano** [comment]
Can you provide more details? How does the network fail? Are you setting configuration on those interfaces manually or are you letting the daemon handle it?

**Comment by oscarr1605** [comment]
First the package is updated, then the daemons restart, after that the network fails.
I share some log captures

![screenshot from 2018-12-19 09-55-42](https://user-images.githubusercontent.com/22629768/50234130-9c9dee00-037a-11e9-8c88-d69871e7feda.png)
![screenshot from 2018-12-19 09-57-43](https://user-images.githubusercontent.com/22629768/50234165-a9224680-037a-11e9-89f2-4d0097831d4b.png)
