### ISSUE TITLE
Expectations for keeping installed package versions recent

### ISSUE THREAD

**Issue by benburry** [GoogleCloudPlatform/compute-image-packages#680]
Hi there.

I'm looking for guidance on what expectations exist in GCP for keeping installed packages up to date on GCE instances, and whether there is a guarantee in place to maintain backwards-compatibility within a certain set of released versions behind HEAD (compatible within the same semver major version, for instance). I'm specifically interested in the centos packages `google-compute-engine` and `python-google-compute-engine`, but I would hope the guidance could apply across all compute-image packages and distros.

In addition, I'd like to be able to watch or be notified for new releases that contain critical updates (for instance, addressing CVEs) that might alter the general guidance around what package versions Google expects to be installed.

Does this package version guidance exist already, or would you be able to supply it? Is there already a process for being notified of critical package releases?

Thanks!

**Comment by illfelder** [comment]
Hi,

Apologies for the delay; there's a lot of questions in your post that make it difficult to give you a single answer. I'll try to answer a simplified version of your post. Feel free to ask followup questions.

This repository is specific to the guest environment installed on Google (and Google-partner) provided Linux based images. It's a codebase that we are constantly improving upon and extending. We treat security flaws very seriously and make updates to the packages as necessary. 

On the CentOS images we publish, we have yum-cron enabled by default. This means standard CentOS policies (dictated by upstream) apply for package updates on a running instance. The latest version of this guest environment will also be pulled in automatically on a running CentOS instance.

Independently, we do try to publish new images when there is a new fix for a CVE. You can view our image releases by following posts to this google group: https://groups.google.com/forum/#!forum/gce-image-notifications

Note that the package versions installed on any of our Google provided images are (with only minor exception) dictated by the upstream distribution.
