### ISSUE TITLE
FreeBSD: sed command in /etc/dhclient-exit-hooks results in duplicate /etc/hosts entries on every reboot

### ISSUE THREAD

**Issue by rhclayto** [GoogleCloudPlatform/compute-image-packages#691]
On FreeBSD Cloud Compute instances, an improper sed command for FreeBSD's version of sed in `/etc/dhclient-exit-hooks` results in duplicate `/etc/hosts` entries on every reboot, like so:

```
10.138.0.2 freebsd-11-2.us-west1-b.c.<hostname>.internal freebsd-11-2  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google
10.138.0.2 freebsd-11-2.us-west1-b.c.<hostname>.internal freebsd-11-2  # Added by Google
169.254.169.254 metadata.google.internal  # Added by Google
```

On every reboot, these lines are appended to, rather than being replaced, so that the hosts file keeps growing with duplicate entries ad infinitum. This results from the following sed command in `/etc/dhclient-exit-hooks`:

`sed -i '/Added by Google/d' /etc/hosts`

On FreeBSD, the sed command with flag -i takes an extension value for the backup file it creates during in-place editing. So here' it's interpreting '/Added by Google/d' as an extension, which doesn't work, so the command fails with the error (when run from the command line) `sed: 1: "/etc/hosts": extra characters at the end of h command`.

The solution is to add an extension to the sed command:

`sed -i .orig '/Added by Google/d' /etc/hosts`

This resolves the problem. It does create an `/etc/hosts.orig` file, which is overwritten every time the sed command is called. If this is undesireable to leave in the filesystem, I suppose the command could be followed by an rm in the `/etc/dhclient-exit-hooks`.

**Comment by hopkiw** [comment]
GNU `sed -i` also takes an extension, which it declares optional:

```
       -i[SUFFIX], --in-place[=SUFFIX]

              edit files in place (makes backup if SUFFIX supplied)
```

FreeBSD sed is documented similarly:
```
     -I	extension
	     Edit files	in-place, saving backups with the specified extension.
	     If	a zero-length extension	is given, no backup will be saved. 
     [...]
     -i	extension
	     Edit files	in-place similarly to -I, but treat each file indepen-
	     dently from other files. 
```

It seems omitting the extension does not count as 'zero-length', so we could create a generalized solution with `sed -i"" <command> <file>`

**Comment by rhclayto** [comment]
Any progress on this? An update undid my local changes. It would be great to see this get merged.

**Comment by hopkiw** [comment]
We tested the change in another script, I'll make the change to this one as well. After pull to development branch, will be waiting on dev->master release.
