### ISSUE TITLE
OS Login Component Overview / PAM inconsistent with google_oslogin_control

### ISSUE THREAD

**Issue by flokli** [GoogleCloudPlatform/compute-image-packages#717]
Currently, the [OS Login Component overwiew](https://github.com/GoogleCloudPlatform/compute-image-packages/tree/master/google_compute_engine_oslogin#components) describes the recommended PAM configuration like this:

```
PAM Module
The pam_module directory contains two modules used by Linux PAM (Pluggable Authentication Modules).

The first module, pam_oslogin_login.so, determines whether a given user is allowed to SSH into an instance. It is activated by adding an account requisite line to the PAM sshd config file and does the following:

[…]

The second module, pam_oslogin_admin.so, determines whether a given user should have admin (sudo) permissions on the instance. It is activated by adding an account optional line to the PAM sshd config file and does the following:

Retrieves the user's profile information from the metadata server.
http://metadata.google.internal/computeMetadata/v1/oslogin/users?username=<username>
If the user is a local user account, the module exits with success.
If the user is an OS Login user, the module perform an authorization check to determine if the user has admin permissions.
http://metadata.google.internal/computeMetadata/v1/oslogin/authorize?email=<user_email>&policy=adminLogin
If the user is authorized as an admin, a file with the username is added to /var/google-sudoers.d/. The file gives the user sudo privileges.
If the authorization check fails for admin permissions, the file is removed from /var/google-sudoers.d/ if it exists.
```

However, configuring `pam_oslogin_login.so` at `account requisite` and `pam_oslogin_admin.so` at `account optional` isn't really true:

`bin/google_oslogin_control` seems to add the following lines to PAM configuration:

```
auth       [success=done perm_denied=bad default=ignore] pam_oslogin_login.so
account    [success=ok default=ignore] pam_oslogin_admin.so
account    [success=ok ignore=ignore default=die] pam_oslogin_login.so
```

This configures `pam_oslogin_login` for both `account` and `auth` management groups (which seems possible, looking at the `PAM_EXTERN` functions), and `pam_oslogin_admin` for `account`, where it's not documented in the text above what happens where.

In addition, the `control` values got a bit more complicated, and it's not documented at which position the oslogin modules should be placed and why. My braindump in why the control values are set like they are:

 - `auth pam_oslogin_login.so` might need to come pretty early, given other pam modules might stumble on the missing usernames
 - `account pam_oslogin_admin.so` with `[success=ok default=ignore]` is even more lax than the historical `optional` - even if it's the only `account` module, other return states (except `PAM_SUCCESS`) don't contribute to the final result of the management group.
 - `account pam_oslogin_login.so` with `[success=ok ignore=ignore default=die]` might imply it should go to the end, as a failure will immediatly terminate further authentication - not sure how well this behaves with other modules that behave like this, too ;-)

Can you clarify here?

In addition, the flow described at that same page is missing the whole flow coded in `pam_sm_authenticate`.

**Comment by hopkiw** [comment]
Thanks for the feedback @flokli - this documentation will be updated shortly based on recent changes and your comments.

The fundamental behavior hasn't changed, but we have made some updates which are out of sync with the documentation. First we are using the new bracket syntax for pam configuration. Comparing the two and referring to `pam.conf(5)` we see that legacy control value `requisite` maps to `[success=ok new_authtok_reqd=ok ignore=ignore default=die]`; we just omitted the `new_authtok_reqd` control as this isn't a possible return value for this module. Legacy control value `optional` maps to ` [success=ok new_authtok_reqd=ok default=ignore]`, with the same omission. So we really haven't changed anything here except to use the new syntax for future-proofing and readability.

The logic by which we make these changes can be gotten from reading the code in `/usr/bin/google_oslogin_control`, but in short: `pam_oslogin_login.so` will be installed in the `auth` stack only if 2-factor is requested, and is placed at the top of the stack and configured to short circuit on success. `pam_oslogin_login.so` and `pam_oslogin_admin.so` will be placed at the end of the `account` stack, to allow existing behavior for these stacks to continue functioning and be supplemented by OS Login features.

Finally, `pam_oslogin_login.so` implements the pam function `pam_sm_acct_mgmt` to validate that an OS Login user exists, and implements the pam function `pam_sm_authenticate` to implement 2-factor authentication. Documentation for the latter will be forthcoming.

**Comment by flokli** [comment]
@hopkiw thanks for the clarification - true, the bracket syntax doesn't introduce new behaviour - am I right you can then also skip the `ignore=ignore` part? I'd also suggest to describe behaviour for each (used) return value, the `default=die` part is a bit scary.

Yes, I did grok through `google_oslogin_control` to figure out how the script tries to configure the system, just wasn't sure about some of the "why"'s:

I'm currently packaging and integrating the oslogin PAM and NSS modules and the ` google_authorized_keys` command into NixOS at https://github.com/NixOS/nixpkgs/pull/51566 - this however requires describing the desired state instead of running scripts reconfiguring services at runtime, so some documentation about the desired end state and reasonings behind help a lot :-)

**Comment by hopkiw** [comment]
> am I right you can then also skip the `ignore=ignore` part, if we strip the scary `default=die`

I'm not sure what the default is if not specified. It isn't specified in `pam.conf(5)`.

**Comment by flokli** [comment]
`default` redefines behaviour on a return code that was not explicitly configured inside the brackets. So I was suggesting to define behaviour for all return codes `pam_oslogin_login.so` can return when used as an account module.

**Comment by flokli** [comment]
Learning from https://github.com/NixOS/nixpkgs/pull/51566#issuecomment-446602369, there should really a bit more verbose documentation in how the module should be configured, and expects other configuration to be, not just the existing shell script - the issue there with `pam_unix` wouldn't have been detected by the script either…
