### ISSUE TITLE
Log startup script and shutdown script output to console when using systemd

### ISSUE THREAD

**Issue by rkolchmeyer** [GoogleCloudPlatform/compute-image-packages#722]
We're interested in logging startup script and shutdown script output to the serial console on COS.  We don't use rsyslog, so I think the best way to do this (for COS) would be to update the corresponding systemd units to output stdout and stderr to journal+console.

We can make this change on our end with a .conf file, but I'm wondering if it might make sense to make that change here. I guess other distros are already solving this problem with rsyslog, so maybe it doesn't make sense to make that change here? I'll send a PR, but if it doesn't make sense, feel free to close. Thanks!

**Comment by illfelder** [comment]
/cc @wonderfly 

COS images carry their own patches for the guest environment. I suspect changes are best made outside of this repo, but I'll share this with the COS maintainers/developers so that they can determine what is most appropriate.
