### ISSUE TITLE
Spinloop on 2FA platforms

### ISSUE THREAD

**Issue by profrowe** [GoogleCloudPlatform/compute-image-packages#726]
**Platform & Version:**
OS:  Debian 9
GCloud Suite Version:
Google Cloud SDK 230.0.0
alpha 2019.01.11
beta 2019.01.11
bq 2.0.39
core 2019.01.11
gsutil 4.35
kubectl 2019.01.11

**Symptoms:**
/var/google-sudoers.d is purged every few seconds.  Even valid roles cannot use os-login to sudo beyond the first few seconds of an SSH session.

**Suspected Cause**
After a lot of auditd tracing, we found the google_accounts_daemon was cycling like a lunatic as follows:
`Jan 17 20:54:11 hostname google-accounts[1110]: INFO Reactivating OS Login with two factor disabled.
Jan 17 20:54:11 hostname google_accounts_daemon[1110]: Deactivating Google Compute Engine OS Login.
Jan 17 20:54:14 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:54:14 hostname google_accounts_daemon[1110]: Activating Google Compute Engine OS Login.
Jan 17 20:54:18 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:55:20 hostname google-accounts[1110]: INFO Reactivating OS Login with two factor disabled.
Jan 17 20:55:20 hostname google_accounts_daemon[1110]: Deactivating Google Compute Engine OS Login.
Jan 17 20:55:23 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:55:23 hostname google_accounts_daemon[1110]: Activating Google Compute Engine OS Login.
Jan 17 20:55:27 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:56:29 hostname google-accounts[1110]: INFO Reactivating OS Login with two factor disabled.
Jan 17 20:56:29 hostname google_accounts_daemon[1110]: Deactivating Google Compute Engine OS Login.
Jan 17 20:56:33 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:56:33 hostname google_accounts_daemon[1110]: Activating Google Compute Engine OS Login.
Jan 17 20:56:36 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:57:38 hostname google-accounts[1110]: INFO Reactivating OS Login with two factor disabled.
Jan 17 20:57:38 hostname google_accounts_daemon[1110]: Deactivating Google Compute Engine OS Login.
Jan 17 20:57:42 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:57:42 hostname google_accounts_daemon[1110]: Activating Google Compute Engine OS Login.
Jan 17 20:57:45 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:58:47 hostname google-accounts[1110]: INFO Reactivating OS Login with two factor disabled.
Jan 17 20:58:47 hostname google_accounts_daemon[1110]: Deactivating Google Compute Engine OS Login.
Jan 17 20:58:51 hostname google_accounts_daemon[1110]: Restarting sshd.
Jan 17 20:58:51 hostname google_accounts_daemon[1110]: Activating Google Compute Engine OS Login.
Jan 17 20:58:54 hostname google_accounts_daemon[1110]: Restarting sshd.
`
This seems to be caused by line 136 of oslogin_utils.py.

Issue is breaking.  Only way to maintain root access is to sudo su on the host within the first few seconds of an SSH session.

**Comment by zmarano** [comment]
Do you have a stable reproduction or a particular setup where this happens? We do not see this issue in our own testing.

**Comment by illfelder** [comment]
Some questions that might help us troubleshoot:

- Are you using a custom image or a Google provided image?
- What image version are your instances running?
- Are these newly created instances, or instances that have updated their guest?
- Is it possible the instances have a new version of the Python package, but and old version of the control file?

**Comment by zmarano** [comment]
Current package versions on Debian 9:
dpkg-query -W "google-compute-engine"
google-compute-engine	2.8.12-1
dpkg-query -W "python-google-compute-engine"
python-google-compute-engine	2.8.12-1
dpkg-query -W "google-compute-engine-oslogin"
google-compute-engine-oslogin	1.4.3-1+deb9

Current control file md5sum:
md5sum /usr/bin/google_oslogin_control
bb6ae2463c9ce08a4580e4d380d6e978  /usr/bin/google_oslogin_control

**Comment by profrowe** [comment]
> Some questions that might help us troubleshoot:
> 
> * Are you using a custom image or a Google provided image?
> * What image version are your instances running?
> * Are these newly created instances, or instances that have updated their guest?
> * Is it possible the instances have a new version of the Python package, but and old version of the control file?

Debian 9, Google provided.  Built on Dec 21 2018.  Python 2.7.13

**Comment by profrowe** [comment]
> Current package versions on Debian 9:
> dpkg-query -W "google-compute-engine"
> google-compute-engine	2.8.12-1
> dpkg-query -W "python-google-compute-engine"
> python-google-compute-engine	2.8.12-1
> dpkg-query -W "google-compute-engine-oslogin"
> google-compute-engine-oslogin	1.4.3-1+deb9
> 
> Current control file md5sum:
> md5sum /usr/bin/google_oslogin_control
> bb6ae2463c9ce08a4580e4d380d6e978 /usr/bin/google_oslogin_control

Everything matches except for the compute-engine-oslogin.  Version 1.3.0-1+deb8 and a different hash.

I did do a:
`gcloud components update` earlier today, which asked me to run `sudo apt-get update && sudo apt-get --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-app-engine-grpc google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-cloud-build-local google-cloud-sdk-datastore-emulator google-cloud-sdk-app-engine-python google-cloud-sdk-cbt google-cloud-sdk-bigtable-emulator google-cloud-sdk-app-engine-python-extras google-cloud-sdk-datalab google-cloud-sdk-app-engine-java`.   There were no errors on the updates.

**Comment by profrowe** [comment]
`apt-get --only-upgrade install google-compute-engine-oslogin
Reading package lists... Done
Building dependency tree
Reading state information... Done
google-compute-engine-oslogin is already the newest version (1.3.0-1+deb8).
The following packages were automatically installed and are no longer required:
  libhiredis0.14 libjemalloc1 liblua5.1-0 linux-image-3.16.0-4-amd64 linux-image-3.16.0-6-amd64 linux-image-4.9.0-6-amd64 lua-bitop lua-cjson redis-tools
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.`

**Comment by zmarano** [comment]
Did you happen to upgrade from Debian 8 to Debian 9 by chance? If so, I think I see what happened here. The repositories for Debian 9 differ from Debian 8 and if you didn't replace the jessie repo's with stretch repo's you will not have the correct packages. The spin loop you see is because the control file is ancient.

Here's the best way to resolve this (as root, or sudo):
Replace /etc/apt/sources.list.d/google-cloud.list to match:
`deb http://packages.cloud.google.com/apt cloud-sdk-stretch main
deb http://packages.cloud.google.com/apt google-compute-engine-stretch-stable main
deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch main`

Then update and upgrade to get the current stretch packages:
apt-get update
apt-get dist-upgrade

Officially, we have not supported a major distro -> major distro version upgrade like this. However, in theory this should replace the appropriate jessie packages with stretch packages.

**Comment by profrowe** [comment]
> Did you happen to upgrade from Debian 8 to Debian 9 by chance? If so, I think I see what happened here. The repositories for Debian 9 differ from Debian 8 and if you didn't replace the jessie repo's with stretch repo's you will not have the correct packages. The spin loop you see is because the control file is ancient.
> 
> Here's the best way to resolve this (as root, or sudo):
> Replace /etc/apt/sources.list.d/google-cloud.list to match:
> `deb http://packages.cloud.google.com/apt cloud-sdk-stretch main`
> `deb http://packages.cloud.google.com/apt google-compute-engine-stretch-stable main`
> `deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch main`
> 
> Then update and upgrade to get the current stretch packages:
> apt-get update
> apt-get dist-upgrade
> 
> Officially, we have not supported a major distro -> major distro version upgrade like this. However, in theory this should replace the appropriate jessie packages with stretch packages.

It's possible.  The person I'd need to ask isn't here currently and bash history is limited.  But I'm seeing jessie in the repo file, not stretch.  I'll go ahead and try and report back.  Thanks.

**Comment by profrowe** [comment]
Well it's been 3 minutes now and the /var/google-sudoers.d hasn't been nuked.  I'll roll this out to the other machines and monitor.  Thanks for your help.  Hopefully this will help anyone else using the jessie repo!

**Comment by zmarano** [comment]
Yes actually you highlighted a problem with our repositories for jessie (which is EOL and no longer supported). But, we will take a look at fixing that repo for any latent jessie users out there and look at these kinds of upgrade paths in the future.
