### ISSUE TITLE
PR #739 replaced packages without bumping version number

### ISSUE THREAD

**Issue by ahayworth** [GoogleCloudPlatform/compute-image-packages#740]
We mirror the google compute engine repo internally, and our mirror sync system ([aptly](https://www.aptly.info/)) has been complaining for several days about sync problems. The latest error is:

> aptly-sync.err:ERROR: unable to import: conflict in package python-google-compute-engine_2.8.13-1_all

It looks like #739 brought in changes to the `python-google-compute-engine` package, but did not bump its version number. The sha256sum is different for each package:
_Downloaded today from packages.cloud.google.com:_
```bash
[Wed Mar 06 10:26] ahayworth@zordon:~/Downloads
$ sha256sum python-google-compute-engine_2.8.13-1_all_413a0823afc8d3a0afea286dbc173796bbc45fe91bd75653007b426ab369b15b.deb
413a0823afc8d3a0afea286dbc173796bbc45fe91bd75653007b426ab369b15b  python-google-compute-engine_2.8.13-1_all_413a0823afc8d3a0afea286dbc173796bbc45fe91bd75653007b426ab369b15b.deb
```

_Last internally synced copy:_
```bash
ahayworth@[pkg server] /data/aptly $ sha256sum ./google-compute-engine-stretch/public/google-compute-engine-stretch/pool/main/g/google-compute-image-packages/python-google-compute-engine_2.8.13-1_all_17ecc5b61826fc3d754e6fc0dc0e158fd1c6507e8da6f284026cb2c4d7a5c1d9.deb
17ecc5b61826fc3d754e6fc0dc0e158fd1c6507e8da6f284026cb2c4d7a5c1d9  ./google-compute-engine-stretch/public/google-compute-engine-stretch/pool/main/g/google-compute-image-packages/python-google-compute-engine_2.8.13-1_all_17ecc5b61826fc3d754e6fc0dc0e158fd1c6507e8da6f284026cb2c4d7a5c1d9.deb
```

Of course, the package filenames include the sha256sum, so it's not really surprising. However, this is generally frowned upon by Debian maintainers, as some archive tools do not deal gracefully with this situation (even if apt clients do).

We've updated things successfully on our end, but this is more of an informational issue to let you know it caused some problems for engineers today. 😄

**Comment by illfelder** [comment]
/cc @hopkiw 

Thanks for this information! It looks like the hash change was caused by the update to the README.

**Comment by hopkiw** [comment]
We are aiming to resolve this by removing any manual steps in the release process other than approval buttons. Leaving the issue open until that's happened, which is expected later this year.

**Comment by ahayworth** [comment]
@hopkiw Thanks for that update, much appreciated. Best of luck in your automation project! 😄
