### ISSUE TITLE
dhclient_script unused in EnableNetworkInterfaces()

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/compute-image-packages#768]
The following block of code takes three parameters (and is called with three parameters), but doesn't use the third parameter at all:

https://github.com/GoogleCloudPlatform/compute-image-packages/blob/53ea8cd069fb4d9a1984d1c167e54c133033f8da/packages/python-google-compute-engine/google_compute_engine/distro_lib/debian_9/utils.py#L26-L35

The code it calls accepts that third parameter, and does things with it, but it never shows up. So it's not clear that `NetworkInterfaces.dhclient_script` in `/etc/default/instance_configs.cfg` ever does anything (at least on a Debian 9 system; looks like RHEL 6 is the only distro that actually passes the argument along).

Of course, the default value for that config, `/sbin/google-dhclient-script` doesn't actually exist on that system; perhaps that's a separate bug.

**Comment by hopkiw** [comment]
you're correct that RHEL6 is the only platform this is actually plumbed through on. the entire feature was originally designed to overcome issues with RHEL6. our plan is to update documentation so this doesn't appear as an exposed feature, do you still need this? how are you working around it today?
