### ISSUE TITLE
/bin/echo -e is not portable

### ISSUE THREAD

**Issue by jayed** [GoogleCloudPlatform/compute-image-packages#776]
[`google_oslogin_control`](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/packages/google-compute-engine-oslogin/bin/google_oslogin_control)  executes:

[`/bin/echo -e "\n\n${sshd_block}\n${sshd_end_block}" >> "$sshd_config"`](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/d2d59253ad3bd219b2834fa6c2fa5b4d2cce4ecc/packages/google-compute-engine-oslogin/bin/google_oslogin_control#L100)

The `-e` flag exists on the Linux version of `/bin/echo` but does not in the FreeBSD version.

The most straight-forward fix that preserves this exact behavior would be:
```shell
printf "\n\n${sshd_block}\n${sshd_end_block}" >> "$sshd_config"
```
All POSIX-compliant shells include `printf`. Its behavior doesn't vary across platforms that I'm aware of.

**Comment by illfelder** [comment]
Thanks for the feedback! I made a pull request following your recommendations.
