### ISSUE TITLE
FreeBSD service command does not output "unrecognized"

### ISSUE THREAD

**Issue by jayed** [GoogleCloudPlatform/compute-image-packages#780]
[google_oslogin_control](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/packages/google-compute-engine-oslogin/bin/google_oslogin_control) uses "unrecognized" to determine if a service exists. FreeBSD does not output this string; instead (for the mythical `bob` service) it outputs
```
bob does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
```
The impact of this is that the attempt to restart a non-existent service fails triggering a roll back of all the changes made.

The [line](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/d2d59253ad3bd219b2834fa6c2fa5b4d2cce4ecc/packages/google-compute-engine-oslogin/bin/google_oslogin_control#L286) is:
```shell
 if ! service "$service" status 2>&1 | grep -q unrecognized; then
```
A fix is to use a `grep` invocation that relies on a regex instead of a straight text match.
```shell
if ! service "$service" status 2>&1 | grep -Eq "unrecognized|does not exist"; then
```

**Comment by illfelder** [comment]
Made a pull request to address with your suggested fix. We just made a new release so it might not make it to our master branch for a little while.
