### ISSUE TITLE
/lib/udev/rules.d/99-gce.rules tries to apply 'scheduler=none' to partitions

### ISSUE THREAD

**Issue by kkm000** [GoogleCloudPlatform/compute-image-packages#783]
This is fairly minor. Maybe I'm reporting this to a wrong repo, because this file is not there, but a search for `filename:99-gce.rules` yields no results on GitHub at all, so maybe you could please buganize (oops, I just verbed a noun) that to whoever owns this file internally? This file exists in the `--image=ubuntu-1804-bionic-v20190514 --image-project=gce-uefi-images`:
```
root@toy-sec-1:~# cat /lib/udev/rules.d/99-gce.rules
# Give syslog write access to the kernel logs
KERNEL=="console", GROUP="syslog", MODE="0620"

# Switch to using NOOP as the default scheduler per GCE request
SUBSYSTEM=="block", ACTION=="add|change", ENV{ID_VENDOR}=="*Google*", ATTR{queue/scheduler}="noop"
```
and the last rule causes these messages logged during boot:
```
Jun  3 04:46:49 toy-sec-1 systemd-udevd[1442]: error opening ATTR{/sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda/sda1/queue/scheduler} for writing: No such file or directory
Jun  3 04:46:49 toy-sec-1 systemd-udevd[1438]: error opening ATTR{/sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda/sda15/queue/scheduler} for writing: No such file or directory
Jun  3 04:46:49 toy-sec-1 systemd-udevd[1437]: error opening ATTR{/sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:1/0:0:1:0/block/sda/sda14/queue/scheduler} for writing: No such file or directory
```
The issue can be also reproduced by running any tool that accesses raw disk, e. g. `parted`: start parted, and all 3 messages are logged; hit ^D to exit, they are logged again.

This error is entirely harmless, but *just not right*. The reason for the error is partition devices, of course, do not have a `queue/scheduler`, only disks do (the `/block/sda/sda1` part of the path). Unfortunately, I do not know what DEVTYPEs can be there in the block subsystem to apply a positive match, but I am sure that excluding partitions in the rule condition would be conservative enough to fix this without breaking anything, like this:
```
SUBSYSTEM=="block", ENV{DEVTYPE}!="partition", ACTION=="add|change", ENV{ID_VENDOR}=="*Google*", ATTR{queue/scheduler}="noop"
```

**Comment by zmarano** [comment]
Ah yes, this is part of the Ubuntu config: https://launchpad.net/ubuntu/+source/gce-compute-image-packages
https://git.launchpad.net/ubuntu/+source/gce-compute-image-packages/tree/debian/99-gce.rules

If you can- make an issue in their source tracker and we'll follow up with them (otherwise we can do that too).

**Comment by kkm000** [comment]
Sure thing, thanks, will do! I have an account there, reported some bugs before.

Funny thing it they just drop it in w/o a package, `dpkg -S` does not point to any source.

If it's their stuff, then just adding `elevator=none` to the kernel command line achieves pretty much the same thing without even involving udev. No matching, no anything, any block device gets the 'none' I/O scheduler by default (and can be later changed by udev rules if needed for e. g. iSCSI).

So the kernels with the `-gcp` suffix are compied by Ubuntu maintainers, too, I guess? Just wondering. They could even compile this in as the default then, and the multi-scsi setting, too. I would if I were them. I/O scheduling in virtio makes little sense really, it's certainly the host's job, as it gets all the actual requests from all guests, and can do its scheduling thing among them all much more efficiently.

**Comment by kkm000** [comment]
X-Ref: https://bugs.launchpad.net/ubuntu/+source/gce-compute-image-packages/+bug/1833660

Thanks again for finding the responsible party! : )

**Comment by hopkiw** [comment]
ubuntu is asking for testers, but claims the bug is fixed. resolving
