### ISSUE TITLE
scripts fail to run on centos 6

### ISSUE THREAD

**Issue by aflat** [GoogleCloudPlatform/compute-image-packages#789]
Centos 6.8, python-google-compute-engine installed via yum. 
Version: python-google-compute-engine.noarch 0:2.8.16-1.el6

[bin]# /opt/rh/python27/root/usr/bin/python2 --version
/opt/rh/python27/root/usr/bin/python2: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

This is due to the python compile. I haven't tracked down in the sources here where that gets done(if it does in this repo) but I know the lib can't be found if you don't have python 2.7 installed. Centos 6.8 has python 2.6.6 by default. To get around this, when you compile python for virtualenv you need to add this to the configure line:
```
--enable-shared LDFLAGS='-Wl,-rpath,\$${ORIGIN}/../lib -Wl,-rpath,\$${ORIGIN}/../usr/lib'
```
Multiple SO solutions as well
https://stackoverflow.com/questions/20842732/libpython2-7-so-1-0-cannot-open-shared-object-file-no-such-file-or-directory
https://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path/1100297#1100297

If your not compiling python, doesn't look like that happens, but again, my search foo is sucking, an alternative is described in the second SO answer

```
python setup.py build_ext --rpath=/opt/rh/python27/root/usr/lib64
```

**Comment by zmarano** [comment]
We ship the packages for each distro's native python version. For CentOS 6, that is python 2.6. If you wanted to use the GCE guest from a different environment outside the supported environment for each distro you can use the version from pip or build your own package for your specific environment. Another good alternative would be to move to CentOS 7 however.

**Comment by aflat** [comment]
I agree that native python for centos 6 is python 2.6.6, but your version is installing python2.7. Note the path /opt/rh/python27/root/usr/lib64, which is where the , which comes from your tools, not the installed version of python from centos 6. Running 

```
python /opt/rh/python27/root/usr/bin/google_metadata_script_runner  --script-type startup --debug
```
works, since it uses the system python, but 

```
/opt/rh/python27/root/usr/bin/google_metadata_script_runner  --script-type startup --debug
```
uses the /opt/rh/python27/root/usr/bin/ python, which fails since it can't load a python 2.7 lib.

**Comment by zmarano** [comment]
Our RPM package for EL6 is for python 2.6. Oh I see what you are looking at. In CentOS/RHEL 6, we also install the python27 SCL environment for gcloud and gsutil to work correctly. And within that environment we install the the library from pypi to handle boto setup. But you shouldn't be running the daemons from the SCL environment- they would conflict with the native ones.

/usr/bin/google_metadata_script_runner is what you want and what all the init scripts are starting.

**Comment by zmarano** [comment]
https://access.redhat.com/solutions/1252913
For SCL, you need to call with `scl enable python27 <path to script>` or source  /opt/rh/python27/enable

**Comment by aflat** [comment]
That would do it, originally I was using python-google-compute-engine-2.8.3-1.el6.noarch from an old custom image, which doesn't have any of those scripts in /usr/bin, so I was debugging why the startup script won't run with the scripts in /opt/rh/....

**Comment by zmarano** [comment]
Yeah- this is one of those funny SCL environment things unfortunately :(
