### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by Dmole** [GoogleCloudPlatform/compute-image-packages#797]
Python it to heavy.
compute-image-packages uses 12% of a small instances RAM.
Port to bash or rust.

**Comment by zmarano** [comment]
Thanks for your report. We are actually working on re-building the guest agent in Go. I do not have an ETA for when we will be ready but it is in progress.

**Comment by Dmole** [comment]
Some benchmarks (energy,time,memory) for language choice;
https://thenewstack.io/which-programming-languages-use-the-least-electricity/
