### ISSUE TITLE
BtrFS support

### ISSUE THREAD

**Issue by renich** [GoogleCloudPlatform/compute-image-packages#81]
Guys, ext4 is boring. Could you support BtrFS? And, while at it, subvolumes.

**Comment by renich** [comment]
Errr.. why is this closed? Why won't you consider BtrFS?

**Comment by zmarano** [comment]
We are deprecating gcimagebundle as a supported tool on GCE- it will still be available in this github project for the time being but no longer maintained or supported on GCE images. There are instructions to replace its functionality here: https://cloud.google.com/compute/docs/creating-custom-image#export_an_image_to_google_cloud_storage

**Comment by renich** [comment]
@zmarano thanks.
