### ISSUE TITLE
Issues sizing GCP instances with RedHat 8

### ISSUE THREAD

**Issue by afernandezody** [GoogleCloudPlatform/compute-image-packages#813]
Hello. I've been spinning up instances on GCP without any issue until a couple of days ago. The problem appears when I select RedHat 8 as the OS as the deployment doesn't resize the hard drive to the input parameter (e.g. 40 GB). No matter which combination of machine and region, the system deploys the instance with the default size (i.e. 10 GB), which is insufficient for most applications. Someone suggested that the problem is related to a known problem and provided me with this link. I'm wondering if anyone has more insight on this issue or knows how to circumvent it? The outputs from the fdisk and df commands are provided below. Thanks. 
```
#sudo fdisk -l
Disk /dev/sda: 40 GiB, 42949672960 bytes, 83886080 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x45fed8bf

#sudo df
Filesystem     1K-blocks    Used Available Use% Mounted on
devtmpfs         1793080       0   1793080   0% /dev
tmpfs            1806916       0   1806916   0% /dev/shm
tmpfs            1806916    8504   1798412   1% /run
tmpfs            1806916       0   1806916   0% /sys/fs/cgroup
/dev/sda1       10474496 2015776   8458720  20% /
tmpfs             361380       0    361380   0% /run/user/1000

**Comment by zmarano** [comment]
This is fixed for RHEL 8 with the new disk-expand package that was released as gce-disk-expand-20190708.00-g1 for RHEL 8.
