### ISSUE TITLE
User home directory permission issue

### ISSUE THREAD

**Issue by yuanzhou** [GoogleCloudPlatform/compute-image-packages#814]
I'm managing the users and groups via Google Cloud Identity. And on GCP I assigned roles to the user groups created on Google Admin Console so I don't have to manually add new members on GCP IAM individually. The problem I'm having now is subdirectories for specific users are created as they log in via OS Login for the first time. But the home directory of each user is set to "drwxr-xr-x.", which can be accessed by other users from other groups. I checked the UMASK is 077 in the `/etc/login.defs`, which should be good. 

How should I control the access permission between user home directories to prevent users from messing up others' home directories?

The hard to do part is the user's home directory is only created the first time they login via OS Login.

Thanks!

**Comment by hopkiw** [comment]
Thanks for the feedback! Home directories for OS Login users are provisioned with the [pam_mkhomedir(8)](https://linux.die.net/man/8/pam_mkhomedir) module, which defaults to a umask of  `0022`. We will update this in the future to take whatever value is set in `/etc/login.defs`

You can unblock yourself today by amending the line in `/etc/pam.d/sshd` from
```
session    [success=ok default=ignore] pam_mkhomedir.so
```

and changing it to
```
session    [success=ok default=ignore] pam_mkhomedir.so umask=0077
```

I've assigned this issue to myself, and will close it when we fix the bug.

**Comment by yuanzhou** [comment]
Thanks! I have a slurm cluster running on GCP. The cluster has controller node, login nodes, and compute nodes. The /home directory is mounted to a NFS filestore instance. In my case, will what you suggested work for the cluster?

**Comment by hopkiw** [comment]
Well for a detailed analysis we might have to open a support case, but based on what you've provided I don't see why it would be an issue. we create home directories in a fairly standard way.

**Comment by yuanzhou** [comment]
Actually I just tried this on the controller node VM and restarted the cluster. Then logged in as a new user whose home directory has not been created before. And this user's directory permission still is "drwxr-xr-x.". I verified this on the login node as well.

Not sure if I should have waited for a while so GCP can have this change populated?

**Comment by hopkiw** [comment]
There is nothing GCP involved, the `pam_mkhomedir` module is a standard linux component. I have also tested this and confirmed the suggested fix above works. before making the change:

```
$ stat -c '%A' $HOME
drwxr-xr-x
```

after making the change and removing the user's home directory, then logging in again to cause it to be created:
```
$ stat -c '%A' $HOME
drwx------
```

This was tested on Debian 9/10 and RHEL 6/7/8, what OS are you using?

**Comment by yuanzhou** [comment]
In my use case, all the VM instances are created with CentOS 7 image from Google. And this is what I get after the change:

![Capture](https://user-images.githubusercontent.com/195873/61988541-92b72a00-aff0-11e9-8729-88d4df316bdd.PNG)

"joe_yuan_midasnetwork_us" is the new user logged after adding the umask change. We'll have lots of users to use the cluster via OS Login.

**Comment by yuanzhou** [comment]
## Update

So I created a new project and installed the slurm cluster. I logged into the controller node and the login node using the admin account, added the "umask=0077" to the `/etc/pam.d/sshd` as you suggested. Then added new users to IAM and tested again. All new users' home directories now have the correct permission on both controller node and the login node!

![Capture](https://user-images.githubusercontent.com/195873/61990012-4bd42f00-b006-11e9-951f-f2559a7de48c.PNG)

I don't know why my old GCP project didn't work, but the new project proofed the solution! Thank you so much for your help!
