### ISSUE TITLE
google-startup-scripts should run BEFORE systemd apt-daily runs

### ISSUE THREAD

**Issue by bvandewalle** [GoogleCloudPlatform/compute-image-packages#815]
I have a startup script which installs a couple packages using apt.
This errors everytime at startup with:
```
INFO startup-script: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
INFO startup-script: E: Unable to lock directory /var/lib/apt/lists/
```

It seems to conflicts with the apt-daily systemd tasks that already took a lock on apt.

This has been solved for Cloud-init:
https://bugs.launchpad.net/cloud-init/+bug/1693361

How can we do this on GCE image? Could this similarly be fixed with the same solution as cloud-init? : 
```
google-startup-scripts should declare itself
Before=apt-daily.service / apt-daily.timer, so that google-startup-scripts takes
precedence over apt-daily on first boot.
```

**Comment by zmarano** [comment]
Thanks for the report!. We'll take a look and test this out.

**Comment by bvandewalle** [comment]
Thanks, In the meantime, I'm using this workaround in my startup script (inspired by https://unix.stackexchange.com/a/315517 ).

Hoping for an official fix soon.

```
systemctl stop apt-daily.service
systemctl stop apt-daily-upgrade.service
systemctl kill --kill-who=all apt-daily.service
systemctl kill --kill-who=all apt-daily-upgrade.service

# wait until `apt-get updated` has been killed
while ! (systemctl list-units --all apt-daily.service | egrep -q '(dead|failed)')
do
  sleep 1;
done
while ! (systemctl list-units --all apt-daily-upgrade.service | egrep -q '(dead|failed)')
do
  sleep 1;
done

Do your apt-get stuff here

# reactivate apt-daily
systemctl start apt-daily.service
systemctl start apt-daily-upgrade.service
```

**Comment by bvandewalle** [comment]
Any news on this @zmarano ? I'm not a huge fan of the hacky solution that I came up above 
Thanks

**Comment by zmarano** [comment]
This was released in the latest guest changes and is in Debian. It will take some time to get this into Ubuntu however.

**Comment by DanielHabenicht** [comment]
> This was released in the latest guest changes and is in Debian. It will take some time to get this into Ubuntu however.

Any update on when this will land in Ubuntu? @zmarano 
I've been running into it lately on `ubuntu-2004-lts`. 

Used this as a workaround: 
```bash
while fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
  echo "waiting for other package installs to complete..."
  sleep 1
done
```
From: https://askubuntu.com/a/373478/1026376

**Comment by hopkiw** [comment]
This issue is from 2019, the change has long since been merged. Spot checked and it is set properly in Ubuntu on GCE. If it doesn't fix for you, that workaround is fine. Also FYI this repository has been deprecated and startup scripts are now located in https://github.com/GoogleCloudPlatform/guest-agent
