### ISSUE TITLE
Git submodules and installation

### ISSUE THREAD

**Issue by renich** [GoogleCloudPlatform/compute-image-packages#82]
Hello,

I'd like to ask you to use submodules. for each project. This way, installation becomes as easy as:

    git clone https://github.com/GoogleCloudPlatform/google-daemon.git
    cd google-daemon
    GIT_WORK_TREE=/ git checkout -f

This last command, will create the files at /; which it's directory structure. The only thing to fix then it's permissions. Git keeps the executable permission, the user and group.

Besides, you won't change your directory structure if yo use sub-modules, while keeping your projects separate and being able to choose which releases to bundle in the compute-image-packages repo.

**Comment by zmarano** [comment]
The guest environment has been entirely rewritten into a coherent python package and associated configs package. Closing this issue out as it is no longer relevant.
