### ISSUE TITLE
Package dependency issue in 16.04 xenial

### ISSUE THREAD

**Issue by jaresty** [GoogleCloudPlatform/compute-image-packages#829]
We discovered today that the python3-google-compute-engine package available at the google apt repositories [1] now has a dependency on packages that are not available on the same upstream canonical repositories that used to work for the previous version of that package. Besides the google package repository, we are also configured to pull from some canonical upstream repositories [2]. The new package has several new dependencies and one of them is currently causing an error when trying to install [3]. We think that this pull request [4] may be causing this new issue. 

[1]
```
deb http://packages.cloud.google.com/apt google-compute-engine-stretch-stable main
deb http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-stretch main
```
[2]
```
deb http://archive.ubuntu.com/ubuntu xenial main universe multiverse
deb http://archive.ubuntu.com/ubuntu xenial-updates main universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main universe multiverse
```
[3]
```
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming. The following information may help to resolve the situation: The following packages have unmet dependencies:
python3-google-compute-engine : Depends: python3-distro but it is not installable
```
[4] https://github.com/GoogleCloudPlatform/compute-image-packages/pull/795/commits/e8b312a4bca725a7544776c10f910b7ccb435511

**Comment by zmarano** [comment]
The packages we publish are for Debian, not Ubuntu. The Ubuntu packages come from the Ubuntu archive and come from their [source](https://launchpad.net/ubuntu/+source/gce-compute-image-packages). As denoted in the repository name, stretch refers to Debian 9 and buster refers to Debian 10. Those packages are not tested or meant to work on Ubuntu.
