### ISSUE TITLE
Arch linux - error: No package owns /usr/lib/libnss_oslogin.so.2

### ISSUE THREAD

**Issue by Strykar** [GoogleCloudPlatform/compute-image-packages#836]
Today, after a year of running Arch on GCE, when I attempt a system upgrade, it fails with:
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra                                                                                                1651.3 KiB  2.78M/s 00:01 [#############################################################################] 100%
 community                                                                                               4.9 MiB  9.89M/s 00:00 [#############################################################################] 100%
 gce is up to date
 custom is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (5) cryptsetup-2.2.0-1  git-2.23.0-1  google-compute-engine-20190801-1  google-compute-engine-oslogin-20190801-1  mercurial-5.1-1

Total Installed Size:  68.94 MiB
Net Upgrade Size:      -0.03 MiB

:: Proceed with installation? [Y/n] y
(5/5) checking keys in keyring                                                                                                  [#############################################################################] 100%
(5/5) checking package integrity                                                                                                [#############################################################################] 100%
(5/5) loading package files                                                                                                     [#############################################################################] 100%
(5/5) checking for file conflicts                                                                                               [#############################################################################] 100%
error: failed to commit transaction (conflicting files)
google-compute-engine-oslogin: /usr/lib/libnss_cache_oslogin.so.2 exists in filesystem
google-compute-engine-oslogin: /usr/lib/libnss_oslogin.so.2 exists in filesystem
Errors occurred, no packages were upgraded.
```

I try to find the package that owns the files in question, and apparently nobody owns it:
```
$ sudo pacman -Qo /usr/lib/libnss_cache_oslogin.so.2
error: No package owns /usr/lib/libnss_cache_oslogin.so.2
$ sudo pacman -Qo /usr/lib/libnss_oslogin.so.2
error: No package owns /usr/lib/libnss_oslogin.so.2
```

And looks like the Makefile always created that symlink:
```
$ ls -l /usr/lib/libnss_cache_oslogin.so.2
lrwxrwxrwx 1 root root 51 Jun 22 12:23 /usr/lib/libnss_cache_oslogin.so.2 -> libnss_cache_google-compute-engine-oslogin-1.5.3.so
$ ls -l /usr/lib/libnss_oslogin.so.2
lrwxrwxrwx 1 root root 45 Jun 22 12:23 /usr/lib/libnss_oslogin.so.2 -> libnss_google-compute-engine-oslogin-1.5.3.so
```
So I'm unsure what's changed or if I should `pacman --overwrite -Syu` those two files for the upgrade to proceed?

**Comment by hopkiw** [comment]
@lcastelli in case there is a change we can make here to the arch package definition to ease the pain for this upgrade.

In the DPKG and RPM package specifications, we recently made a change to indicate that we own these symlinks, which we were not doing before. The arch packages seem to be built from one of these, and it sounds like pacman is a bit picky about declaring ownership of existing files. I'd say the best thing to do would be to manually remove the package and the symlinks, then install the newer version, though Lorenzo can correct me if there's a better method specific to arch. Sorry for your trouble!

Oh, also worth noting that the OS Login components have been relocated and are now at https://github.com/GoogleCloudPlatform/guest-oslogin

**Comment by lcastelli** [comment]
For updating to the new version, you can run the following command:
```
sudo pacman -Syu --overwrite "/usr/lib/libnss_oslogin.so.2,/usr/lib/libnss_cache_oslogin.so.2"
```

I put a note about it on the [package page](https://aur.archlinux.org/packages/google-compute-engine-oslogin/) on arch. You might want to refer to that page if there are issues in the future.

@hopkiw unfortunately I don't think there is a way around having to run a special update command on Arch. In fact this is a pretty common occurrence for Arch updates: if you head to https://www.archlinux.org/, you can see most notices are about the same problem on different packages :)

Thanks for the heads up on the new guest-oslogin repository!

**Comment by Strykar** [comment]
@hopkiw Uninstalling `google-compute-engine` and `google-compute-engine-oslogin` does indeed remove the two symlinks, it appears the packages did not claim ownership of it before. Reinstalling the packages and updating appears to work fine.
@lcastelli I was following https://aur.archlinux.org/pkgbase/google-compute-engine/ upto now, will also follow the other package now for future updates.
