### ISSUE TITLE
Sudoers should be managed in /etc/sudoers.d

### ISSUE THREAD

**Issue by renich** [GoogleCloudPlatform/compute-image-packages#85]
According to sudo's recommendation, you should add a file or individual files in the /etc/sudoers.d directory.

Also, currently, when I remove a user, it lingers on the /etc/sudoers file. It should be removed, IMHO.

If the first recommendation is implemented by using individual files, the second should be easy to do.

Sorry for the two issues in one ;)

**Comment by illfelder** [comment]
The latest GitHub release contains the new Linux guest environment which manages sudo access with a sudoers group.
