### ISSUE TITLE
Private key logged in dmesg

### ISSUE THREAD

**Issue by gavinatpan** [GoogleCloudPlatform/compute-image-packages#852]
Line 149 can log malformed private keys through dmesg:
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/packages/python-google-compute-engine/google_compute_engine/accounts/accounts_daemon.py#L149

Probably a better way to log this problem than copying the entire private key into logger.info line by line.

**Comment by illfelder** [comment]
Metadata is only intended to store SSH public keys. The accounts daemon reads these SSH public keys and configures them for local user accounts. SSH private keys should never leave the machine where they are generated and should not get logged by the accounts daemon.

**Comment by gavinatpan** [comment]
I see documentation asserts, "Copy and paste the contents of your public SSH key file into the text box."
However, the UI says, "Enter entire key data".  Someone in our team misunderstood and wrote some automation that tried to insert the private key, which line #149 dutifully logged in its entirety.

**Comment by illfelder** [comment]
Ah, makes sense. We can file a bug for the UI team to make their message more clear. As a side note, you might want to consider using OS Login (the Google recommended way to connect to GCE instances). OS Login does not copy SSH keys into the VM and does not use SSH key set in metadata; SSH keys are stored as part of the user and access is determined at log in time based on IAM permissions.

https://cloud.google.com/compute/docs/oslogin

**Comment by illfelder** [comment]
I filed a bug for the UI team to make the message more clear. We'll leave the guest behavior as-is since it makes the supported use case easier to debug.
