### ISSUE TITLE
OSLogin sudo doesn't work when disk is full

### ISSUE THREAD

**Issue by kustodian** [GoogleCloudPlatform/compute-image-packages#853]
If the disk is full OSLogin sudo stops working, which makes it impossible to become root (when using official GCE CentOS 7 images at least).

I guess the problem is because OSLogin service on the instance creates a file in `/var/google-sudoers.d` which is then used by sudo, but because the disk is full that file cannot be created. Not exactly sure what is the best way to fix this issue, but because OSLogin is the Google recommended way of login, it should be possible to login using OSLogin and run sudo even if the disk space is full.

**Comment by colinleroy** [comment]
@zmarano how has this been completed? (the problem still exists on existing instances)

**Comment by zmarano** [comment]
@dorileo may be able to help answer that question for you :)

**Comment by colinleroy** [comment]
In the meantime, we're using tmpfs mounts to workaround this issue:
```
$ grep google /etc/fstab 
tmpfs /var/google-users.d tmpfs size=10M,mode=0750,uid=0,gid=0 0 0
tmpfs /var/google-sudoers.d tmpfs size=10M,mode=0750,uid=0,gid=0 0 0
```
