### ISSUE TITLE
Instance setup should set scheduler to `none` on systems using blk-mq

### ISSUE THREAD

**Issue by hopkiw** [GoogleCloudPlatform/compute-image-packages#856]
There's no kernel parameter for this yet; it must be done from userspace after boot.

**Comment by tetianakravchenko** [comment]
@hopkiw isn't scheduler set by udev rules defined in https://launchpad.net/ubuntu/+source/gce-compute-image-packages:

```
cat /lib/udev/rules.d/99-gce.rules 
# Give syslog write access to the kernel logs
KERNEL=="console", GROUP="syslog", MODE="0620"
# Switch to using NOOP as the default scheduler per GCE request
SUBSYSTEM=="block", ENV{DEVTYPE}!="partition", ACTION=="add|change", ENV{ID_VENDOR}=="*Google*", ATTR{queue/schedul
er}="noop"
```
for new kernel (> 5.3 https://wiki.ubuntu.com/Kernel/Reference/IOSchedulers) it should be `none`, not `noop`
