### ISSUE TITLE
Fix CentOS dependencies for syslog and revert back syslog restart.

### ISSUE THREAD

**Issue by billouellette** [GoogleCloudPlatform/compute-image-packages#897]
We are currently unable to use Syslog-NG on CentOS images due to dependency on Rsyslog.

This is the same issue as https://github.com/GoogleCloudPlatform/compute-image-packages/issues/548

**Comment by fdr** [comment]
I can confirm that as of today there is a hard dependency on rsyslog, so swapping to syslog-ng will uninstall crucial packages. Caused me quite a bit of confusion as to why SSH keys, browser SSH, startup-scripts were not functional.
