### ISSUE TITLE
Ubuntu 16.04.07 error trying to overwrite '/etc/dhcp/dhclient-exit-hooks.d/google_set_hostname

### ISSUE THREAD

**Issue by kapilsingh421** [GoogleCloudPlatform/compute-image-packages#904]
Hey,

I was trying to upgrade ubuntu but getting this while running command ( sudo apt-get update && sudo apt-get upgrade -f)

Do you want to continue? [Y/n] Y
Get:1 http://europe-west4-b.gce.clouds.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 google-compute-engine all 20201222.00-0ubuntu2~16.04.0 [12.9 kB]
Fetched 12.9 kB in 0s (44.1 kB/s)          
(Reading database ... 175234 files and directories currently installed.)
Preparing to unpack .../google-compute-engine_20201222.00-0ubuntu2~16.04.0_all.deb ...
Unpacking google-compute-engine (20201222.00-0ubuntu2~16.04.0) ...
dpkg: error processing archive /var/cache/apt/archives/google-compute-engine_20201222.00-0ubuntu2~16.04.0_all.deb (--unpack):
 trying to overwrite '/etc/dhcp/dhclient-exit-hooks.d/google_set_hostname', which is also in package gce-compute-image-packages 20201222.00-0ubuntu2~16.04.0
Errors were encountered while processing:
 /var/cache/apt/archives/google-compute-engine_20201222.00-0ubuntu2~16.04.0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

<img width="1280" alt="Screenshot 2021-04-20 at 12 14 51 PM" src="https://user-images.githubusercontent.com/37150928/115349934-13a95280-a1d2-11eb-9603-3eb4b3a35309.png">

**Comment by gilbert-hsu** [comment]
same as Ubuntu 18.04
