### ISSUE TITLE
Debian 11.9 latest security update not available in GCE yet

### ISSUE THREAD

**Issue by amrutha-shanbhag** [GoogleCloudPlatform/compute-image-packages#908]
Debian 11 latest image containing security updates was released on 29/04/2024. https://cloud.debian.org/images/cloud/bullseye/20240429-1732/ . When can we expect the corresponding image in GCE?

**Comment by zmarano** [comment]
Debian images are updated monthly and thus there will be a new Debian 11 image next week (we generally follow the second Tuesday of the month approach).

https://cloud.google.com/compute/docs/images/os-image-lifecycle#eos-policy

**Comment by amrutha-shanbhag** [comment]
great, thanks!
